#
# Makefile for the DCE plugin for OMAP DRM driver.  This driver provides
# support for hw accellerated video decode/encode.
#

ccflags-y := -Werror
omapdce-y := dce.o

obj-$(CONFIG_VIDEO_OMAP_DCE)	+= omapdce.o
