 # Makefile for sensor chip drivers.
 #
obj-$(CONFIG_TMP102_SENSOR)	+= tmp102_temp_sensor.o
obj-$(CONFIG_TMP006_SENSOR)	+= tmp006_temp_sensor.o
obj-$(CONFIG_OMAP5_THERMAL)	+= omap5-thermal.o
obj-$(CONFIG_CASE_TEMP_SENSOR)	+= case_temp_sensor.o

ccflags-y := -Idrivers/thermal
