#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_THERMAL)		+= thermal_sys.o
obj-$(CONFIG_SPEAR_THERMAL)		+= spear_thermal.o
obj-$(CONFIG_OMAP_BANDGAP)	+= omap-thermal.o
omap-thermal-y			:= omap-bandgap.o
