/*
 * ALSA SoC OMAP ABE driver
*
 * Author:          Laurent Le Faucheur <l-le-faucheur@ti.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */
#ifndef _ABE_SM_ADDR_H_
#define _ABE_SM_ADDR_H_
#define init_SM_ADDR                                        0
#define init_SM_ADDR_END                                    305
#define init_SM_sizeof                                      306
#define S_Data0_ADDR                                        306
#define S_Data0_ADDR_END                                    306
#define S_Data0_sizeof                                      1
#define S_Temp_ADDR                                         307
#define S_Temp_ADDR_END                                     307
#define S_Temp_sizeof                                       1
#define S_PhoenixOffset_ADDR                                308
#define S_PhoenixOffset_ADDR_END                            308
#define S_PhoenixOffset_sizeof                              1
#define S_GTarget1_ADDR                                     309
#define S_GTarget1_ADDR_END                                 315
#define S_GTarget1_sizeof                                   7
#define S_Gtarget_DL1_ADDR                                  316
#define S_Gtarget_DL1_ADDR_END                              317
#define S_Gtarget_DL1_sizeof                                2
#define S_Gtarget_DL2_ADDR                                  318
#define S_Gtarget_DL2_ADDR_END                              319
#define S_Gtarget_DL2_sizeof                                2
#define S_Gtarget_Echo_ADDR                                 320
#define S_Gtarget_Echo_ADDR_END                             320
#define S_Gtarget_Echo_sizeof                               1
#define S_Gtarget_SDT_ADDR                                  321
#define S_Gtarget_SDT_ADDR_END                              321
#define S_Gtarget_SDT_sizeof                                1
#define S_Gtarget_VxRec_ADDR                                322
#define S_Gtarget_VxRec_ADDR_END                            323
#define S_Gtarget_VxRec_sizeof                              2
#define S_Gtarget_UL_ADDR                                   324
#define S_Gtarget_UL_ADDR_END                               325
#define S_Gtarget_UL_sizeof                                 2
#define S_Gtarget_unused_ADDR                               326
#define S_Gtarget_unused_ADDR_END                           326
#define S_Gtarget_unused_sizeof                             1
#define S_GCurrent_ADDR                                     327
#define S_GCurrent_ADDR_END                                 344
#define S_GCurrent_sizeof                                   18
#define S_GAIN_ONE_ADDR                                     345
#define S_GAIN_ONE_ADDR_END                                 345
#define S_GAIN_ONE_sizeof                                   1
#define S_Tones_ADDR                                        346
#define S_Tones_ADDR_END                                    357
#define S_Tones_sizeof                                      12
#define S_VX_DL_ADDR                                        358
#define S_VX_DL_ADDR_END                                    369
#define S_VX_DL_sizeof                                      12
#define S_MM_UL2_ADDR                                       370
#define S_MM_UL2_ADDR_END                                   381
#define S_MM_UL2_sizeof                                     12
#define S_MM_DL_ADDR                                        382
#define S_MM_DL_ADDR_END                                    393
#define S_MM_DL_sizeof                                      12
#define S_DL1_M_Out_ADDR                                    394
#define S_DL1_M_Out_ADDR_END                                405
#define S_DL1_M_Out_sizeof                                  12
#define S_DL2_M_Out_ADDR                                    406
#define S_DL2_M_Out_ADDR_END                                417
#define S_DL2_M_Out_sizeof                                  12
#define S_Echo_M_Out_ADDR                                   418
#define S_Echo_M_Out_ADDR_END                               429
#define S_Echo_M_Out_sizeof                                 12
#define S_SDT_M_Out_ADDR                                    430
#define S_SDT_M_Out_ADDR_END                                441
#define S_SDT_M_Out_sizeof                                  12
#define S_VX_UL_ADDR                                        442
#define S_VX_UL_ADDR_END                                    453
#define S_VX_UL_sizeof                                      12
#define S_VX_UL_M_ADDR                                      454
#define S_VX_UL_M_ADDR_END                                  465
#define S_VX_UL_M_sizeof                                    12
#define S_BT_DL_ADDR                                        466
#define S_BT_DL_ADDR_END                                    477
#define S_BT_DL_sizeof                                      12
#define S_BT_UL_ADDR                                        478
#define S_BT_UL_ADDR_END                                    489
#define S_BT_UL_sizeof                                      12
#define S_BT_DL_8k_ADDR                                     490
#define S_BT_DL_8k_ADDR_END                                 491
#define S_BT_DL_8k_sizeof                                   2
#define S_BT_DL_16k_ADDR                                    492
#define S_BT_DL_16k_ADDR_END                                495
#define S_BT_DL_16k_sizeof                                  4
#define S_BT_UL_8k_ADDR                                     496
#define S_BT_UL_8k_ADDR_END                                 497
#define S_BT_UL_8k_sizeof                                   2
#define S_BT_UL_16k_ADDR                                    498
#define S_BT_UL_16k_ADDR_END                                501
#define S_BT_UL_16k_sizeof                                  4
#define S_SDT_F_ADDR                                        502
#define S_SDT_F_ADDR_END                                    513
#define S_SDT_F_sizeof                                      12
#define S_SDT_F_data_ADDR                                   514
#define S_SDT_F_data_ADDR_END                               522
#define S_SDT_F_data_sizeof                                 9
#define S_MM_DL_OSR_ADDR                                    523
#define S_MM_DL_OSR_ADDR_END                                546
#define S_MM_DL_OSR_sizeof                                  24
#define S_24_zeros_ADDR                                     547
#define S_24_zeros_ADDR_END                                 570
#define S_24_zeros_sizeof                                   24
#define S_DMIC1_ADDR                                        571
#define S_DMIC1_ADDR_END                                    582
#define S_DMIC1_sizeof                                      12
#define S_DMIC2_ADDR                                        583
#define S_DMIC2_ADDR_END                                    594
#define S_DMIC2_sizeof                                      12
#define S_DMIC3_ADDR                                        595
#define S_DMIC3_ADDR_END                                    606
#define S_DMIC3_sizeof                                      12
#define S_AMIC_ADDR                                         607
#define S_AMIC_ADDR_END                                     618
#define S_AMIC_sizeof                                       12
#define S_EANC_FBK_in_ADDR                                  619
#define S_EANC_FBK_in_ADDR_END                              642
#define S_EANC_FBK_in_sizeof                                24
#define S_EANC_FBK_out_ADDR                                 643
#define S_EANC_FBK_out_ADDR_END                             654
#define S_EANC_FBK_out_sizeof                               12
#define S_DMIC1_L_ADDR                                      655
#define S_DMIC1_L_ADDR_END                                  666
#define S_DMIC1_L_sizeof                                    12
#define S_DMIC1_R_ADDR                                      667
#define S_DMIC1_R_ADDR_END                                  678
#define S_DMIC1_R_sizeof                                    12
#define S_DMIC2_L_ADDR                                      679
#define S_DMIC2_L_ADDR_END                                  690
#define S_DMIC2_L_sizeof                                    12
#define S_DMIC2_R_ADDR                                      691
#define S_DMIC2_R_ADDR_END                                  702
#define S_DMIC2_R_sizeof                                    12
#define S_DMIC3_L_ADDR                                      703
#define S_DMIC3_L_ADDR_END                                  714
#define S_DMIC3_L_sizeof                                    12
#define S_DMIC3_R_ADDR                                      715
#define S_DMIC3_R_ADDR_END                                  726
#define S_DMIC3_R_sizeof                                    12
#define S_BT_UL_L_ADDR                                      727
#define S_BT_UL_L_ADDR_END                                  738
#define S_BT_UL_L_sizeof                                    12
#define S_BT_UL_R_ADDR                                      739
#define S_BT_UL_R_ADDR_END                                  750
#define S_BT_UL_R_sizeof                                    12
#define S_AMIC_L_ADDR                                       751
#define S_AMIC_L_ADDR_END                                   762
#define S_AMIC_L_sizeof                                     12
#define S_AMIC_R_ADDR                                       763
#define S_AMIC_R_ADDR_END                                   774
#define S_AMIC_R_sizeof                                     12
#define S_EANC_FBK_L_ADDR                                   775
#define S_EANC_FBK_L_ADDR_END                               786
#define S_EANC_FBK_L_sizeof                                 12
#define S_EANC_FBK_R_ADDR                                   787
#define S_EANC_FBK_R_ADDR_END                               798
#define S_EANC_FBK_R_sizeof                                 12
#define S_EchoRef_L_ADDR                                    799
#define S_EchoRef_L_ADDR_END                                810
#define S_EchoRef_L_sizeof                                  12
#define S_EchoRef_R_ADDR                                    811
#define S_EchoRef_R_ADDR_END                                822
#define S_EchoRef_R_sizeof                                  12
#define S_MM_DL_L_ADDR                                      823
#define S_MM_DL_L_ADDR_END                                  834
#define S_MM_DL_L_sizeof                                    12
#define S_MM_DL_R_ADDR                                      835
#define S_MM_DL_R_ADDR_END                                  846
#define S_MM_DL_R_sizeof                                    12
#define S_MM_UL_ADDR                                        847
#define S_MM_UL_ADDR_END                                    966
#define S_MM_UL_sizeof                                      120
#define S_AMIC_96k_ADDR                                     967
#define S_AMIC_96k_ADDR_END                                 990
#define S_AMIC_96k_sizeof                                   24
#define S_DMIC0_96k_ADDR                                    991
#define S_DMIC0_96k_ADDR_END                                1014
#define S_DMIC0_96k_sizeof                                  24
#define S_DMIC1_96k_ADDR                                    1015
#define S_DMIC1_96k_ADDR_END                                1038
#define S_DMIC1_96k_sizeof                                  24
#define S_DMIC2_96k_ADDR                                    1039
#define S_DMIC2_96k_ADDR_END                                1062
#define S_DMIC2_96k_sizeof                                  24
#define S_UL_VX_UL_48_8K_ADDR                               1063
#define S_UL_VX_UL_48_8K_ADDR_END                           1074
#define S_UL_VX_UL_48_8K_sizeof                             12
#define S_UL_VX_UL_48_16K_ADDR                              1075
#define S_UL_VX_UL_48_16K_ADDR_END                          1086
#define S_UL_VX_UL_48_16K_sizeof                            12
#define S_UL_MIC_48K_ADDR                                   1087
#define S_UL_MIC_48K_ADDR_END                               1098
#define S_UL_MIC_48K_sizeof                                 12
#define S_Voice_8k_UL_ADDR                                  1099
#define S_Voice_8k_UL_ADDR_END                              1101
#define S_Voice_8k_UL_sizeof                                3
#define S_Voice_8k_DL_ADDR                                  1102
#define S_Voice_8k_DL_ADDR_END                              1103
#define S_Voice_8k_DL_sizeof                                2
#define S_McPDM_Out1_ADDR                                   1104
#define S_McPDM_Out1_ADDR_END                               1127
#define S_McPDM_Out1_sizeof                                 24
#define S_McPDM_Out2_ADDR                                   1128
#define S_McPDM_Out2_ADDR_END                               1151
#define S_McPDM_Out2_sizeof                                 24
#define S_McPDM_Out3_ADDR                                   1152
#define S_McPDM_Out3_ADDR_END                               1175
#define S_McPDM_Out3_sizeof                                 24
#define S_Voice_16k_UL_ADDR                                 1176
#define S_Voice_16k_UL_ADDR_END                             1180
#define S_Voice_16k_UL_sizeof                               5
#define S_Voice_16k_DL_ADDR                                 1181
#define S_Voice_16k_DL_ADDR_END                             1184
#define S_Voice_16k_DL_sizeof                               4
#define S_XinASRC_DL_VX_ADDR                                1185
#define S_XinASRC_DL_VX_ADDR_END                            1224
#define S_XinASRC_DL_VX_sizeof                              40
#define S_XinASRC_UL_VX_ADDR                                1225
#define S_XinASRC_UL_VX_ADDR_END                            1264
#define S_XinASRC_UL_VX_sizeof                              40
#define S_XinASRC_MM_EXT_IN_ADDR                            1265
#define S_XinASRC_MM_EXT_IN_ADDR_END                        1304
#define S_XinASRC_MM_EXT_IN_sizeof                          40
#define S_VX_REC_ADDR                                       1305
#define S_VX_REC_ADDR_END                                   1316
#define S_VX_REC_sizeof                                     12
#define S_VX_REC_L_ADDR                                     1317
#define S_VX_REC_L_ADDR_END                                 1328
#define S_VX_REC_L_sizeof                                   12
#define S_VX_REC_R_ADDR                                     1329
#define S_VX_REC_R_ADDR_END                                 1340
#define S_VX_REC_R_sizeof                                   12
#define S_DL2_M_L_ADDR                                      1341
#define S_DL2_M_L_ADDR_END                                  1352
#define S_DL2_M_L_sizeof                                    12
#define S_DL2_M_R_ADDR                                      1353
#define S_DL2_M_R_ADDR_END                                  1364
#define S_DL2_M_R_sizeof                                    12
#define S_DL2_M_LR_EQ_data_ADDR                             1365
#define S_DL2_M_LR_EQ_data_ADDR_END                         1389
#define S_DL2_M_LR_EQ_data_sizeof                           25
#define S_DL1_M_EQ_data_ADDR                                1390
#define S_DL1_M_EQ_data_ADDR_END                            1414
#define S_DL1_M_EQ_data_sizeof                              25
#define S_EARP_48_96_LP_data_ADDR                           1415
#define S_EARP_48_96_LP_data_ADDR_END                       1429
#define S_EARP_48_96_LP_data_sizeof                         15
#define S_IHF_48_96_LP_data_ADDR                            1430
#define S_IHF_48_96_LP_data_ADDR_END                        1444
#define S_IHF_48_96_LP_data_sizeof                          15
#define S_VX_UL_8_TEMP_ADDR                                 1445
#define S_VX_UL_8_TEMP_ADDR_END                             1446
#define S_VX_UL_8_TEMP_sizeof                               2
#define S_VX_UL_16_TEMP_ADDR                                1447
#define S_VX_UL_16_TEMP_ADDR_END                            1450
#define S_VX_UL_16_TEMP_sizeof                              4
#define S_VX_DL_8_48_LP_data_ADDR                           1451
#define S_VX_DL_8_48_LP_data_ADDR_END                       1461
#define S_VX_DL_8_48_LP_data_sizeof                         11
#define S_VX_DL_8_48_HP_data_ADDR                           1462
#define S_VX_DL_8_48_HP_data_ADDR_END                       1468
#define S_VX_DL_8_48_HP_data_sizeof                         7
#define S_VX_DL_16_48_LP_data_ADDR                          1469
#define S_VX_DL_16_48_LP_data_ADDR_END                      1479
#define S_VX_DL_16_48_LP_data_sizeof                        11
#define S_VX_DL_16_48_HP_data_ADDR                          1480
#define S_VX_DL_16_48_HP_data_ADDR_END                      1484
#define S_VX_DL_16_48_HP_data_sizeof                        5
#define S_VX_UL_48_8_LP_data_ADDR                           1485
#define S_VX_UL_48_8_LP_data_ADDR_END                       1495
#define S_VX_UL_48_8_LP_data_sizeof                         11
#define S_VX_UL_48_8_HP_data_ADDR                           1496
#define S_VX_UL_48_8_HP_data_ADDR_END                       1502
#define S_VX_UL_48_8_HP_data_sizeof                         7
#define S_VX_UL_48_16_LP_data_ADDR                          1503
#define S_VX_UL_48_16_LP_data_ADDR_END                      1513
#define S_VX_UL_48_16_LP_data_sizeof                        11
#define S_VX_UL_48_16_HP_data_ADDR                          1514
#define S_VX_UL_48_16_HP_data_ADDR_END                      1520
#define S_VX_UL_48_16_HP_data_sizeof                        7
#define S_BT_UL_8_48_LP_data_ADDR                           1521
#define S_BT_UL_8_48_LP_data_ADDR_END                       1531
#define S_BT_UL_8_48_LP_data_sizeof                         11
#define S_BT_UL_8_48_HP_data_ADDR                           1532
#define S_BT_UL_8_48_HP_data_ADDR_END                       1538
#define S_BT_UL_8_48_HP_data_sizeof                         7
#define S_BT_UL_16_48_LP_data_ADDR                          1539
#define S_BT_UL_16_48_LP_data_ADDR_END                      1549
#define S_BT_UL_16_48_LP_data_sizeof                        11
#define S_BT_UL_16_48_HP_data_ADDR                          1550
#define S_BT_UL_16_48_HP_data_ADDR_END                      1554
#define S_BT_UL_16_48_HP_data_sizeof                        5
#define S_BT_DL_48_8_LP_data_ADDR                           1555
#define S_BT_DL_48_8_LP_data_ADDR_END                       1565
#define S_BT_DL_48_8_LP_data_sizeof                         11
#define S_BT_DL_48_8_HP_data_ADDR                           1566
#define S_BT_DL_48_8_HP_data_ADDR_END                       1572
#define S_BT_DL_48_8_HP_data_sizeof                         7
#define S_BT_DL_48_16_LP_data_ADDR                          1573
#define S_BT_DL_48_16_LP_data_ADDR_END                      1583
#define S_BT_DL_48_16_LP_data_sizeof                        11
#define S_BT_DL_48_16_HP_data_ADDR                          1584
#define S_BT_DL_48_16_HP_data_ADDR_END                      1588
#define S_BT_DL_48_16_HP_data_sizeof                        5
#define S_ECHO_REF_48_8_LP_data_ADDR                        1589
#define S_ECHO_REF_48_8_LP_data_ADDR_END                    1599
#define S_ECHO_REF_48_8_LP_data_sizeof                      11
#define S_ECHO_REF_48_8_HP_data_ADDR                        1600
#define S_ECHO_REF_48_8_HP_data_ADDR_END                    1606
#define S_ECHO_REF_48_8_HP_data_sizeof                      7
#define S_ECHO_REF_48_16_LP_data_ADDR                       1607
#define S_ECHO_REF_48_16_LP_data_ADDR_END                   1617
#define S_ECHO_REF_48_16_LP_data_sizeof                     11
#define S_ECHO_REF_48_16_HP_data_ADDR                       1618
#define S_ECHO_REF_48_16_HP_data_ADDR_END                   1622
#define S_ECHO_REF_48_16_HP_data_sizeof                     5
#define S_EANC_IIR_data_ADDR                                1623
#define S_EANC_IIR_data_ADDR_END                            1639
#define S_EANC_IIR_data_sizeof                              17
#define S_EANC_SignalTemp_ADDR                              1640
#define S_EANC_SignalTemp_ADDR_END                          1660
#define S_EANC_SignalTemp_sizeof                            21
#define S_EANC_Input_ADDR                                   1661
#define S_EANC_Input_ADDR_END                               1661
#define S_EANC_Input_sizeof                                 1
#define S_EANC_Output_ADDR                                  1662
#define S_EANC_Output_ADDR_END                              1662
#define S_EANC_Output_sizeof                                1
#define S_APS_IIRmem1_ADDR                                  1663
#define S_APS_IIRmem1_ADDR_END                              1671
#define S_APS_IIRmem1_sizeof                                9
#define S_APS_M_IIRmem2_ADDR                                1672
#define S_APS_M_IIRmem2_ADDR_END                            1674
#define S_APS_M_IIRmem2_sizeof                              3
#define S_APS_C_IIRmem2_ADDR                                1675
#define S_APS_C_IIRmem2_ADDR_END                            1677
#define S_APS_C_IIRmem2_sizeof                              3
#define S_APS_DL1_OutSamples_ADDR                           1678
#define S_APS_DL1_OutSamples_ADDR_END                       1679
#define S_APS_DL1_OutSamples_sizeof                         2
#define S_APS_DL1_COIL_OutSamples_ADDR                      1680
#define S_APS_DL1_COIL_OutSamples_ADDR_END                  1681
#define S_APS_DL1_COIL_OutSamples_sizeof                    2
#define S_APS_DL2_L_OutSamples_ADDR                         1682
#define S_APS_DL2_L_OutSamples_ADDR_END                     1683
#define S_APS_DL2_L_OutSamples_sizeof                       2
#define S_APS_DL2_L_COIL_OutSamples_ADDR                    1684
#define S_APS_DL2_L_COIL_OutSamples_ADDR_END                1685
#define S_APS_DL2_L_COIL_OutSamples_sizeof                  2
#define S_APS_DL2_R_OutSamples_ADDR                         1686
#define S_APS_DL2_R_OutSamples_ADDR_END                     1687
#define S_APS_DL2_R_OutSamples_sizeof                       2
#define S_APS_DL2_R_COIL_OutSamples_ADDR                    1688
#define S_APS_DL2_R_COIL_OutSamples_ADDR_END                1689
#define S_APS_DL2_R_COIL_OutSamples_sizeof                  2
#define S_XinASRC_ECHO_REF_ADDR                             1690
#define S_XinASRC_ECHO_REF_ADDR_END                         1729
#define S_XinASRC_ECHO_REF_sizeof                           40
#define S_ECHO_REF_16K_ADDR                                 1730
#define S_ECHO_REF_16K_ADDR_END                             1734
#define S_ECHO_REF_16K_sizeof                               5
#define S_ECHO_REF_8K_ADDR                                  1735
#define S_ECHO_REF_8K_ADDR_END                              1737
#define S_ECHO_REF_8K_sizeof                                3
#define S_DL1_EQ_ADDR                                       1738
#define S_DL1_EQ_ADDR_END                                   1749
#define S_DL1_EQ_sizeof                                     12
#define S_DL2_EQ_ADDR                                       1750
#define S_DL2_EQ_ADDR_END                                   1761
#define S_DL2_EQ_sizeof                                     12
#define S_DL1_GAIN_out_ADDR                                 1762
#define S_DL1_GAIN_out_ADDR_END                             1773
#define S_DL1_GAIN_out_sizeof                               12
#define S_DL2_GAIN_out_ADDR                                 1774
#define S_DL2_GAIN_out_ADDR_END                             1785
#define S_DL2_GAIN_out_sizeof                               12
#define S_APS_DL2_L_IIRmem1_ADDR                            1786
#define S_APS_DL2_L_IIRmem1_ADDR_END                        1794
#define S_APS_DL2_L_IIRmem1_sizeof                          9
#define S_APS_DL2_R_IIRmem1_ADDR                            1795
#define S_APS_DL2_R_IIRmem1_ADDR_END                        1803
#define S_APS_DL2_R_IIRmem1_sizeof                          9
#define S_APS_DL2_L_M_IIRmem2_ADDR                          1804
#define S_APS_DL2_L_M_IIRmem2_ADDR_END                      1806
#define S_APS_DL2_L_M_IIRmem2_sizeof                        3
#define S_APS_DL2_R_M_IIRmem2_ADDR                          1807
#define S_APS_DL2_R_M_IIRmem2_ADDR_END                      1809
#define S_APS_DL2_R_M_IIRmem2_sizeof                        3
#define S_APS_DL2_L_C_IIRmem2_ADDR                          1810
#define S_APS_DL2_L_C_IIRmem2_ADDR_END                      1812
#define S_APS_DL2_L_C_IIRmem2_sizeof                        3
#define S_APS_DL2_R_C_IIRmem2_ADDR                          1813
#define S_APS_DL2_R_C_IIRmem2_ADDR_END                      1815
#define S_APS_DL2_R_C_IIRmem2_sizeof                        3
#define S_DL1_APS_ADDR                                      1816
#define S_DL1_APS_ADDR_END                                  1827
#define S_DL1_APS_sizeof                                    12
#define S_DL2_L_APS_ADDR                                    1828
#define S_DL2_L_APS_ADDR_END                                1839
#define S_DL2_L_APS_sizeof                                  12
#define S_DL2_R_APS_ADDR                                    1840
#define S_DL2_R_APS_ADDR_END                                1851
#define S_DL2_R_APS_sizeof                                  12
#define S_APS_DL1_EQ_data_ADDR                              1852
#define S_APS_DL1_EQ_data_ADDR_END                          1860
#define S_APS_DL1_EQ_data_sizeof                            9
#define S_APS_DL2_EQ_data_ADDR                              1861
#define S_APS_DL2_EQ_data_ADDR_END                          1869
#define S_APS_DL2_EQ_data_sizeof                            9
#define S_DC_DCvalue_ADDR                                   1870
#define S_DC_DCvalue_ADDR_END                               1870
#define S_DC_DCvalue_sizeof                                 1
#define S_VIBRA_ADDR                                        1871
#define S_VIBRA_ADDR_END                                    1876
#define S_VIBRA_sizeof                                      6
#define S_Vibra2_in_ADDR                                    1877
#define S_Vibra2_in_ADDR_END                                1882
#define S_Vibra2_in_sizeof                                  6
#define S_Vibra2_addr_ADDR                                  1883
#define S_Vibra2_addr_ADDR_END                              1883
#define S_Vibra2_addr_sizeof                                1
#define S_VibraCtrl_forRightSM_ADDR                         1884
#define S_VibraCtrl_forRightSM_ADDR_END                     1907
#define S_VibraCtrl_forRightSM_sizeof                       24
#define S_Rnoise_mem_ADDR                                   1908
#define S_Rnoise_mem_ADDR_END                               1908
#define S_Rnoise_mem_sizeof                                 1
#define S_Ctrl_ADDR                                         1909
#define S_Ctrl_ADDR_END                                     1926
#define S_Ctrl_sizeof                                       18
#define S_Vibra1_in_ADDR                                    1927
#define S_Vibra1_in_ADDR_END                                1932
#define S_Vibra1_in_sizeof                                  6
#define S_Vibra1_temp_ADDR                                  1933
#define S_Vibra1_temp_ADDR_END                              1956
#define S_Vibra1_temp_sizeof                                24
#define S_VibraCtrl_forLeftSM_ADDR                          1957
#define S_VibraCtrl_forLeftSM_ADDR_END                      1980
#define S_VibraCtrl_forLeftSM_sizeof                        24
#define S_Vibra1_mem_ADDR                                   1981
#define S_Vibra1_mem_ADDR_END                               1991
#define S_Vibra1_mem_sizeof                                 11
#define S_VibraCtrl_Stereo_ADDR                             1992
#define S_VibraCtrl_Stereo_ADDR_END                         2015
#define S_VibraCtrl_Stereo_sizeof                           24
#define S_AMIC_96_48_data_ADDR                              2016
#define S_AMIC_96_48_data_ADDR_END                          2034
#define S_AMIC_96_48_data_sizeof                            19
#define S_DMIC0_96_48_data_ADDR                             2035
#define S_DMIC0_96_48_data_ADDR_END                         2053
#define S_DMIC0_96_48_data_sizeof                           19
#define S_DMIC1_96_48_data_ADDR                             2054
#define S_DMIC1_96_48_data_ADDR_END                         2072
#define S_DMIC1_96_48_data_sizeof                           19
#define S_DMIC2_96_48_data_ADDR                             2073
#define S_DMIC2_96_48_data_ADDR_END                         2091
#define S_DMIC2_96_48_data_sizeof                           19
#define S_EANC_FBK_96_48_data_ADDR                          2092
#define S_EANC_FBK_96_48_data_ADDR_END                      2110
#define S_EANC_FBK_96_48_data_sizeof                        19
#define S_DBG_8K_PATTERN_ADDR                               2111
#define S_DBG_8K_PATTERN_ADDR_END                           2112
#define S_DBG_8K_PATTERN_sizeof                             2
#define S_DBG_16K_PATTERN_ADDR                              2113
#define S_DBG_16K_PATTERN_ADDR_END                          2116
#define S_DBG_16K_PATTERN_sizeof                            4
#define S_DBG_24K_PATTERN_ADDR                              2117
#define S_DBG_24K_PATTERN_ADDR_END                          2122
#define S_DBG_24K_PATTERN_sizeof                            6
#define S_DBG_48K_PATTERN_ADDR                              2123
#define S_DBG_48K_PATTERN_ADDR_END                          2134
#define S_DBG_48K_PATTERN_sizeof                            12
#define S_DBG_96K_PATTERN_ADDR                              2135
#define S_DBG_96K_PATTERN_ADDR_END                          2158
#define S_DBG_96K_PATTERN_sizeof                            24
#define S_MM_EXT_IN_ADDR                                    2159
#define S_MM_EXT_IN_ADDR_END                                2170
#define S_MM_EXT_IN_sizeof                                  12
#define S_MM_EXT_IN_L_ADDR                                  2171
#define S_MM_EXT_IN_L_ADDR_END                              2182
#define S_MM_EXT_IN_L_sizeof                                12
#define S_MM_EXT_IN_R_ADDR                                  2183
#define S_MM_EXT_IN_R_ADDR_END                              2194
#define S_MM_EXT_IN_R_sizeof                                12
#define S_MIC4_ADDR                                         2195
#define S_MIC4_ADDR_END                                     2206
#define S_MIC4_sizeof                                       12
#define S_MIC4_L_ADDR                                       2207
#define S_MIC4_L_ADDR_END                                   2218
#define S_MIC4_L_sizeof                                     12
#define S_MIC4_R_ADDR                                       2219
#define S_MIC4_R_ADDR_END                                   2230
#define S_MIC4_R_sizeof                                     12
#define S_HW_TEST_ADDR                                      2231
#define S_HW_TEST_ADDR_END                                  2231
#define S_HW_TEST_sizeof                                    1
#endif/* _ABESM_ADDR_H_ */
