/*
 * ALSA SoC OMAP ABE driver
*
 * Author:          Laurent Le Faucheur <l-le-faucheur@ti.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */
#ifndef _ABE_CM_ADDR_H_
#define _ABE_CM_ADDR_H_
#define init_CM_ADDR                                        0
#define init_CM_ADDR_END                                    305
#define init_CM_sizeof                                      306
#define C_Data_LSB_2_ADDR                                   306
#define C_Data_LSB_2_ADDR_END                               306
#define C_Data_LSB_2_sizeof                                 1
#define C_1_Alpha_ADDR                                      307
#define C_1_Alpha_ADDR_END                                  324
#define C_1_Alpha_sizeof                                    18
#define C_Alpha_ADDR                                        325
#define C_Alpha_ADDR_END                                    342
#define C_Alpha_sizeof                                      18
#define C_GainsWRamp_ADDR                                   343
#define C_GainsWRamp_ADDR_END                               356
#define C_GainsWRamp_sizeof                                 14
#define C_Gains_DL1M_ADDR                                   357
#define C_Gains_DL1M_ADDR_END                               360
#define C_Gains_DL1M_sizeof                                 4
#define C_Gains_DL2M_ADDR                                   361
#define C_Gains_DL2M_ADDR_END                               364
#define C_Gains_DL2M_sizeof                                 4
#define C_Gains_EchoM_ADDR                                  365
#define C_Gains_EchoM_ADDR_END                              366
#define C_Gains_EchoM_sizeof                                2
#define C_Gains_SDTM_ADDR                                   367
#define C_Gains_SDTM_ADDR_END                               368
#define C_Gains_SDTM_sizeof                                 2
#define C_Gains_VxRecM_ADDR                                 369
#define C_Gains_VxRecM_ADDR_END                             372
#define C_Gains_VxRecM_sizeof                               4
#define C_Gains_ULM_ADDR                                    373
#define C_Gains_ULM_ADDR_END                                376
#define C_Gains_ULM_sizeof                                  4
#define C_Gains_unused_ADDR                                 377
#define C_Gains_unused_ADDR_END                             378
#define C_Gains_unused_sizeof                               2
#define C_SDT_Coefs_ADDR                                    379
#define C_SDT_Coefs_ADDR_END                                387
#define C_SDT_Coefs_sizeof                                  9
#define C_CoefASRC1_VX_ADDR                                 388
#define C_CoefASRC1_VX_ADDR_END                             406
#define C_CoefASRC1_VX_sizeof                               19
#define C_CoefASRC2_VX_ADDR                                 407
#define C_CoefASRC2_VX_ADDR_END                             425
#define C_CoefASRC2_VX_sizeof                               19
#define C_CoefASRC3_VX_ADDR                                 426
#define C_CoefASRC3_VX_ADDR_END                             444
#define C_CoefASRC3_VX_sizeof                               19
#define C_CoefASRC4_VX_ADDR                                 445
#define C_CoefASRC4_VX_ADDR_END                             463
#define C_CoefASRC4_VX_sizeof                               19
#define C_CoefASRC5_VX_ADDR                                 464
#define C_CoefASRC5_VX_ADDR_END                             482
#define C_CoefASRC5_VX_sizeof                               19
#define C_CoefASRC6_VX_ADDR                                 483
#define C_CoefASRC6_VX_ADDR_END                             501
#define C_CoefASRC6_VX_sizeof                               19
#define C_CoefASRC7_VX_ADDR                                 502
#define C_CoefASRC7_VX_ADDR_END                             520
#define C_CoefASRC7_VX_sizeof                               19
#define C_CoefASRC8_VX_ADDR                                 521
#define C_CoefASRC8_VX_ADDR_END                             539
#define C_CoefASRC8_VX_sizeof                               19
#define C_CoefASRC9_VX_ADDR                                 540
#define C_CoefASRC9_VX_ADDR_END                             558
#define C_CoefASRC9_VX_sizeof                               19
#define C_CoefASRC10_VX_ADDR                                559
#define C_CoefASRC10_VX_ADDR_END                            577
#define C_CoefASRC10_VX_sizeof                              19
#define C_CoefASRC11_VX_ADDR                                578
#define C_CoefASRC11_VX_ADDR_END                            596
#define C_CoefASRC11_VX_sizeof                              19
#define C_CoefASRC12_VX_ADDR                                597
#define C_CoefASRC12_VX_ADDR_END                            615
#define C_CoefASRC12_VX_sizeof                              19
#define C_CoefASRC13_VX_ADDR                                616
#define C_CoefASRC13_VX_ADDR_END                            634
#define C_CoefASRC13_VX_sizeof                              19
#define C_CoefASRC14_VX_ADDR                                635
#define C_CoefASRC14_VX_ADDR_END                            653
#define C_CoefASRC14_VX_sizeof                              19
#define C_CoefASRC15_VX_ADDR                                654
#define C_CoefASRC15_VX_ADDR_END                            672
#define C_CoefASRC15_VX_sizeof                              19
#define C_CoefASRC16_VX_ADDR                                673
#define C_CoefASRC16_VX_ADDR_END                            691
#define C_CoefASRC16_VX_sizeof                              19
#define C_AlphaCurrent_UL_VX_ADDR                           692
#define C_AlphaCurrent_UL_VX_ADDR_END                       692
#define C_AlphaCurrent_UL_VX_sizeof                         1
#define C_BetaCurrent_UL_VX_ADDR                            693
#define C_BetaCurrent_UL_VX_ADDR_END                        693
#define C_BetaCurrent_UL_VX_sizeof                          1
#define C_AlphaCurrent_DL_VX_ADDR                           694
#define C_AlphaCurrent_DL_VX_ADDR_END                       694
#define C_AlphaCurrent_DL_VX_sizeof                         1
#define C_BetaCurrent_DL_VX_ADDR                            695
#define C_BetaCurrent_DL_VX_ADDR_END                        695
#define C_BetaCurrent_DL_VX_sizeof                          1
#define C_CoefASRC1_MM_ADDR                                 696
#define C_CoefASRC1_MM_ADDR_END                             713
#define C_CoefASRC1_MM_sizeof                               18
#define C_CoefASRC2_MM_ADDR                                 714
#define C_CoefASRC2_MM_ADDR_END                             731
#define C_CoefASRC2_MM_sizeof                               18
#define C_CoefASRC3_MM_ADDR                                 732
#define C_CoefASRC3_MM_ADDR_END                             749
#define C_CoefASRC3_MM_sizeof                               18
#define C_CoefASRC4_MM_ADDR                                 750
#define C_CoefASRC4_MM_ADDR_END                             767
#define C_CoefASRC4_MM_sizeof                               18
#define C_CoefASRC5_MM_ADDR                                 768
#define C_CoefASRC5_MM_ADDR_END                             785
#define C_CoefASRC5_MM_sizeof                               18
#define C_CoefASRC6_MM_ADDR                                 786
#define C_CoefASRC6_MM_ADDR_END                             803
#define C_CoefASRC6_MM_sizeof                               18
#define C_CoefASRC7_MM_ADDR                                 804
#define C_CoefASRC7_MM_ADDR_END                             821
#define C_CoefASRC7_MM_sizeof                               18
#define C_CoefASRC8_MM_ADDR                                 822
#define C_CoefASRC8_MM_ADDR_END                             839
#define C_CoefASRC8_MM_sizeof                               18
#define C_CoefASRC9_MM_ADDR                                 840
#define C_CoefASRC9_MM_ADDR_END                             857
#define C_CoefASRC9_MM_sizeof                               18
#define C_CoefASRC10_MM_ADDR                                858
#define C_CoefASRC10_MM_ADDR_END                            875
#define C_CoefASRC10_MM_sizeof                              18
#define C_CoefASRC11_MM_ADDR                                876
#define C_CoefASRC11_MM_ADDR_END                            893
#define C_CoefASRC11_MM_sizeof                              18
#define C_CoefASRC12_MM_ADDR                                894
#define C_CoefASRC12_MM_ADDR_END                            911
#define C_CoefASRC12_MM_sizeof                              18
#define C_CoefASRC13_MM_ADDR                                912
#define C_CoefASRC13_MM_ADDR_END                            929
#define C_CoefASRC13_MM_sizeof                              18
#define C_CoefASRC14_MM_ADDR                                930
#define C_CoefASRC14_MM_ADDR_END                            947
#define C_CoefASRC14_MM_sizeof                              18
#define C_CoefASRC15_MM_ADDR                                948
#define C_CoefASRC15_MM_ADDR_END                            965
#define C_CoefASRC15_MM_sizeof                              18
#define C_CoefASRC16_MM_ADDR                                966
#define C_CoefASRC16_MM_ADDR_END                            983
#define C_CoefASRC16_MM_sizeof                              18
#define C_AlphaCurrent_MM_EXT_IN_ADDR                       984
#define C_AlphaCurrent_MM_EXT_IN_ADDR_END                   984
#define C_AlphaCurrent_MM_EXT_IN_sizeof                     1
#define C_BetaCurrent_MM_EXT_IN_ADDR                        985
#define C_BetaCurrent_MM_EXT_IN_ADDR_END                    985
#define C_BetaCurrent_MM_EXT_IN_sizeof                      1
#define C_DL2_L_Coefs_ADDR                                  986
#define C_DL2_L_Coefs_ADDR_END                              1010
#define C_DL2_L_Coefs_sizeof                                25
#define C_DL2_R_Coefs_ADDR                                  1011
#define C_DL2_R_Coefs_ADDR_END                              1035
#define C_DL2_R_Coefs_sizeof                                25
#define C_DL1_Coefs_ADDR                                    1036
#define C_DL1_Coefs_ADDR_END                                1060
#define C_DL1_Coefs_sizeof                                  25
#define C_SRC_3_LP_Coefs_ADDR                               1061
#define C_SRC_3_LP_Coefs_ADDR_END                           1071
#define C_SRC_3_LP_Coefs_sizeof                             11
#define C_SRC_3_LP_GAIN_Coefs_ADDR                          1072
#define C_SRC_3_LP_GAIN_Coefs_ADDR_END                      1082
#define C_SRC_3_LP_GAIN_Coefs_sizeof                        11
#define C_SRC_3_HP_Coefs_ADDR                               1083
#define C_SRC_3_HP_Coefs_ADDR_END                           1087
#define C_SRC_3_HP_Coefs_sizeof                             5
#define C_SRC_6_LP_Coefs_ADDR                               1088
#define C_SRC_6_LP_Coefs_ADDR_END                           1098
#define C_SRC_6_LP_Coefs_sizeof                             11
#define C_SRC_6_LP_GAIN_Coefs_ADDR                          1099
#define C_SRC_6_LP_GAIN_Coefs_ADDR_END                      1109
#define C_SRC_6_LP_GAIN_Coefs_sizeof                        11
#define C_SRC_6_HP_Coefs_ADDR                               1110
#define C_SRC_6_HP_Coefs_ADDR_END                           1116
#define C_SRC_6_HP_Coefs_sizeof                             7
#define C_EANC_WarpCoeffs_ADDR                              1117
#define C_EANC_WarpCoeffs_ADDR_END                          1118
#define C_EANC_WarpCoeffs_sizeof                            2
#define C_EANC_FIRcoeffs_ADDR                               1119
#define C_EANC_FIRcoeffs_ADDR_END                           1139
#define C_EANC_FIRcoeffs_sizeof                             21
#define C_EANC_IIRcoeffs_ADDR                               1140
#define C_EANC_IIRcoeffs_ADDR_END                           1156
#define C_EANC_IIRcoeffs_sizeof                             17
#define C_EANC_FIRcoeffs_2nd_ADDR                           1157
#define C_EANC_FIRcoeffs_2nd_ADDR_END                       1177
#define C_EANC_FIRcoeffs_2nd_sizeof                         21
#define C_EANC_IIRcoeffs_2nd_ADDR                           1178
#define C_EANC_IIRcoeffs_2nd_ADDR_END                       1194
#define C_EANC_IIRcoeffs_2nd_sizeof                         17
#define C_APS_DL1_coeffs1_ADDR                              1195
#define C_APS_DL1_coeffs1_ADDR_END                          1203
#define C_APS_DL1_coeffs1_sizeof                            9
#define C_APS_DL1_M_coeffs2_ADDR                            1204
#define C_APS_DL1_M_coeffs2_ADDR_END                        1206
#define C_APS_DL1_M_coeffs2_sizeof                          3
#define C_APS_DL1_C_coeffs2_ADDR                            1207
#define C_APS_DL1_C_coeffs2_ADDR_END                        1209
#define C_APS_DL1_C_coeffs2_sizeof                          3
#define C_APS_DL2_L_coeffs1_ADDR                            1210
#define C_APS_DL2_L_coeffs1_ADDR_END                        1218
#define C_APS_DL2_L_coeffs1_sizeof                          9
#define C_APS_DL2_R_coeffs1_ADDR                            1219
#define C_APS_DL2_R_coeffs1_ADDR_END                        1227
#define C_APS_DL2_R_coeffs1_sizeof                          9
#define C_APS_DL2_L_M_coeffs2_ADDR                          1228
#define C_APS_DL2_L_M_coeffs2_ADDR_END                      1230
#define C_APS_DL2_L_M_coeffs2_sizeof                        3
#define C_APS_DL2_R_M_coeffs2_ADDR                          1231
#define C_APS_DL2_R_M_coeffs2_ADDR_END                      1233
#define C_APS_DL2_R_M_coeffs2_sizeof                        3
#define C_APS_DL2_L_C_coeffs2_ADDR                          1234
#define C_APS_DL2_L_C_coeffs2_ADDR_END                      1236
#define C_APS_DL2_L_C_coeffs2_sizeof                        3
#define C_APS_DL2_R_C_coeffs2_ADDR                          1237
#define C_APS_DL2_R_C_coeffs2_ADDR_END                      1239
#define C_APS_DL2_R_C_coeffs2_sizeof                        3
#define C_AlphaCurrent_ECHO_REF_ADDR                        1240
#define C_AlphaCurrent_ECHO_REF_ADDR_END                    1240
#define C_AlphaCurrent_ECHO_REF_sizeof                      1
#define C_BetaCurrent_ECHO_REF_ADDR                         1241
#define C_BetaCurrent_ECHO_REF_ADDR_END                     1241
#define C_BetaCurrent_ECHO_REF_sizeof                       1
#define C_APS_DL1_EQ_ADDR                                   1242
#define C_APS_DL1_EQ_ADDR_END                               1250
#define C_APS_DL1_EQ_sizeof                                 9
#define C_APS_DL2_L_EQ_ADDR                                 1251
#define C_APS_DL2_L_EQ_ADDR_END                             1259
#define C_APS_DL2_L_EQ_sizeof                               9
#define C_APS_DL2_R_EQ_ADDR                                 1260
#define C_APS_DL2_R_EQ_ADDR_END                             1268
#define C_APS_DL2_R_EQ_sizeof                               9
#define C_Vibra2_consts_ADDR                                1269
#define C_Vibra2_consts_ADDR_END                            1272
#define C_Vibra2_consts_sizeof                              4
#define C_Vibra1_coeffs_ADDR                                1273
#define C_Vibra1_coeffs_ADDR_END                            1283
#define C_Vibra1_coeffs_sizeof                              11
#define C_48_96_LP_Coefs_ADDR                               1284
#define C_48_96_LP_Coefs_ADDR_END                           1298
#define C_48_96_LP_Coefs_sizeof                             15
#define C_96_48_AMIC_Coefs_ADDR                             1299
#define C_96_48_AMIC_Coefs_ADDR_END                         1317
#define C_96_48_AMIC_Coefs_sizeof                           19
#define C_96_48_DMIC_Coefs_ADDR                             1318
#define C_96_48_DMIC_Coefs_ADDR_END                         1336
#define C_96_48_DMIC_Coefs_sizeof                           19
#define C_INPUT_SCALE_ADDR                                  1337
#define C_INPUT_SCALE_ADDR_END                              1337
#define C_INPUT_SCALE_sizeof                                1
#define C_OUTPUT_SCALE_ADDR                                 1338
#define C_OUTPUT_SCALE_ADDR_END                             1338
#define C_OUTPUT_SCALE_sizeof                               1
#define C_MUTE_SCALING_ADDR                                 1339
#define C_MUTE_SCALING_ADDR_END                             1339
#define C_MUTE_SCALING_sizeof                               1
#define C_GAINS_0DB_ADDR                                    1340
#define C_GAINS_0DB_ADDR_END                                1341
#define C_GAINS_0DB_sizeof                                  2
#endif/* _ABECM_ADDR_H_ */
