/*
 * ALSA SoC OMAP ABE driver
*
 * Author:          Laurent Le Faucheur <l-le-faucheur@ti.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */
#ifndef _ABE_SM_ADDR_H_
#define _ABE_SM_ADDR_H_
#define init_SM_ADDR                                        0
#define init_SM_ADDR_END                                    310
#define init_SM_sizeof                                      311
#define S_Data0_ADDR                                        311
#define S_Data0_ADDR_END                                    311
#define S_Data0_sizeof                                      1
#define S_Temp_ADDR                                         312
#define S_Temp_ADDR_END                                     312
#define S_Temp_sizeof                                       1
#define S_PhoenixOffset_ADDR                                313
#define S_PhoenixOffset_ADDR_END                            313
#define S_PhoenixOffset_sizeof                              1
#define S_GTarget1_ADDR                                     314
#define S_GTarget1_ADDR_END                                 320
#define S_GTarget1_sizeof                                   7
#define S_Gtarget_DL1_ADDR                                  321
#define S_Gtarget_DL1_ADDR_END                              322
#define S_Gtarget_DL1_sizeof                                2
#define S_Gtarget_DL2_ADDR                                  323
#define S_Gtarget_DL2_ADDR_END                              324
#define S_Gtarget_DL2_sizeof                                2
#define S_Gtarget_Echo_ADDR                                 325
#define S_Gtarget_Echo_ADDR_END                             325
#define S_Gtarget_Echo_sizeof                               1
#define S_Gtarget_SDT_ADDR                                  326
#define S_Gtarget_SDT_ADDR_END                              326
#define S_Gtarget_SDT_sizeof                                1
#define S_Gtarget_VxRec_ADDR                                327
#define S_Gtarget_VxRec_ADDR_END                            328
#define S_Gtarget_VxRec_sizeof                              2
#define S_Gtarget_UL_ADDR                                   329
#define S_Gtarget_UL_ADDR_END                               330
#define S_Gtarget_UL_sizeof                                 2
#define S_Gtarget_BTUL_ADDR                                 331
#define S_Gtarget_BTUL_ADDR_END                             331
#define S_Gtarget_BTUL_sizeof                               1
#define S_GCurrent_ADDR                                     332
#define S_GCurrent_ADDR_END                                 349
#define S_GCurrent_sizeof                                   18
#define S_GAIN_ONE_ADDR                                     350
#define S_GAIN_ONE_ADDR_END                                 350
#define S_GAIN_ONE_sizeof                                   1
#define S_Tones_ADDR                                        351
#define S_Tones_ADDR_END                                    362
#define S_Tones_sizeof                                      12
#define S_VX_DL_ADDR                                        363
#define S_VX_DL_ADDR_END                                    374
#define S_VX_DL_sizeof                                      12
#define S_MM_UL2_ADDR                                       375
#define S_MM_UL2_ADDR_END                                   386
#define S_MM_UL2_sizeof                                     12
#define S_MM_DL_ADDR                                        387
#define S_MM_DL_ADDR_END                                    398
#define S_MM_DL_sizeof                                      12
#define S_DL1_M_Out_ADDR                                    399
#define S_DL1_M_Out_ADDR_END                                410
#define S_DL1_M_Out_sizeof                                  12
#define S_DL2_M_Out_ADDR                                    411
#define S_DL2_M_Out_ADDR_END                                422
#define S_DL2_M_Out_sizeof                                  12
#define S_Echo_M_Out_ADDR                                   423
#define S_Echo_M_Out_ADDR_END                               434
#define S_Echo_M_Out_sizeof                                 12
#define S_SDT_M_Out_ADDR                                    435
#define S_SDT_M_Out_ADDR_END                                446
#define S_SDT_M_Out_sizeof                                  12
#define S_VX_UL_ADDR                                        447
#define S_VX_UL_ADDR_END                                    458
#define S_VX_UL_sizeof                                      12
#define S_VX_UL_M_ADDR                                      459
#define S_VX_UL_M_ADDR_END                                  470
#define S_VX_UL_M_sizeof                                    12
#define S_BT_DL_ADDR                                        471
#define S_BT_DL_ADDR_END                                    482
#define S_BT_DL_sizeof                                      12
#define S_BT_UL_ADDR                                        483
#define S_BT_UL_ADDR_END                                    494
#define S_BT_UL_sizeof                                      12
#define S_BT_DL_8k_ADDR                                     495
#define S_BT_DL_8k_ADDR_END                                 497
#define S_BT_DL_8k_sizeof                                   3
#define S_BT_DL_16k_ADDR                                    498
#define S_BT_DL_16k_ADDR_END                                502
#define S_BT_DL_16k_sizeof                                  5
#define S_BT_UL_8k_ADDR                                     503
#define S_BT_UL_8k_ADDR_END                                 504
#define S_BT_UL_8k_sizeof                                   2
#define S_BT_UL_16k_ADDR                                    505
#define S_BT_UL_16k_ADDR_END                                508
#define S_BT_UL_16k_sizeof                                  4
#define S_SDT_F_ADDR                                        509
#define S_SDT_F_ADDR_END                                    520
#define S_SDT_F_sizeof                                      12
#define S_SDT_F_data_ADDR                                   521
#define S_SDT_F_data_ADDR_END                               529
#define S_SDT_F_data_sizeof                                 9
#define S_MM_DL_OSR_ADDR                                    530
#define S_MM_DL_OSR_ADDR_END                                553
#define S_MM_DL_OSR_sizeof                                  24
#define S_24_zeros_ADDR                                     554
#define S_24_zeros_ADDR_END                                 577
#define S_24_zeros_sizeof                                   24
#define S_DMIC1_ADDR                                        578
#define S_DMIC1_ADDR_END                                    589
#define S_DMIC1_sizeof                                      12
#define S_DMIC2_ADDR                                        590
#define S_DMIC2_ADDR_END                                    601
#define S_DMIC2_sizeof                                      12
#define S_DMIC3_ADDR                                        602
#define S_DMIC3_ADDR_END                                    613
#define S_DMIC3_sizeof                                      12
#define S_AMIC_ADDR                                         614
#define S_AMIC_ADDR_END                                     625
#define S_AMIC_sizeof                                       12
#define S_DMIC1_L_ADDR                                      626
#define S_DMIC1_L_ADDR_END                                  637
#define S_DMIC1_L_sizeof                                    12
#define S_DMIC1_R_ADDR                                      638
#define S_DMIC1_R_ADDR_END                                  649
#define S_DMIC1_R_sizeof                                    12
#define S_DMIC2_L_ADDR                                      650
#define S_DMIC2_L_ADDR_END                                  661
#define S_DMIC2_L_sizeof                                    12
#define S_DMIC2_R_ADDR                                      662
#define S_DMIC2_R_ADDR_END                                  673
#define S_DMIC2_R_sizeof                                    12
#define S_DMIC3_L_ADDR                                      674
#define S_DMIC3_L_ADDR_END                                  685
#define S_DMIC3_L_sizeof                                    12
#define S_DMIC3_R_ADDR                                      686
#define S_DMIC3_R_ADDR_END                                  697
#define S_DMIC3_R_sizeof                                    12
#define S_BT_UL_L_ADDR                                      698
#define S_BT_UL_L_ADDR_END                                  709
#define S_BT_UL_L_sizeof                                    12
#define S_BT_UL_R_ADDR                                      710
#define S_BT_UL_R_ADDR_END                                  721
#define S_BT_UL_R_sizeof                                    12
#define S_AMIC_L_ADDR                                       722
#define S_AMIC_L_ADDR_END                                   733
#define S_AMIC_L_sizeof                                     12
#define S_AMIC_R_ADDR                                       734
#define S_AMIC_R_ADDR_END                                   745
#define S_AMIC_R_sizeof                                     12
#define S_EchoRef_L_ADDR                                    746
#define S_EchoRef_L_ADDR_END                                757
#define S_EchoRef_L_sizeof                                  12
#define S_EchoRef_R_ADDR                                    758
#define S_EchoRef_R_ADDR_END                                769
#define S_EchoRef_R_sizeof                                  12
#define S_MM_DL_L_ADDR                                      770
#define S_MM_DL_L_ADDR_END                                  781
#define S_MM_DL_L_sizeof                                    12
#define S_MM_DL_R_ADDR                                      782
#define S_MM_DL_R_ADDR_END                                  793
#define S_MM_DL_R_sizeof                                    12
#define S_MM_UL_ADDR                                        794
#define S_MM_UL_ADDR_END                                    913
#define S_MM_UL_sizeof                                      120
#define S_AMIC_96k_ADDR                                     914
#define S_AMIC_96k_ADDR_END                                 937
#define S_AMIC_96k_sizeof                                   24
#define S_DMIC0_96k_ADDR                                    938
#define S_DMIC0_96k_ADDR_END                                961
#define S_DMIC0_96k_sizeof                                  24
#define S_DMIC1_96k_ADDR                                    962
#define S_DMIC1_96k_ADDR_END                                985
#define S_DMIC1_96k_sizeof                                  24
#define S_DMIC2_96k_ADDR                                    986
#define S_DMIC2_96k_ADDR_END                                1009
#define S_DMIC2_96k_sizeof                                  24
#define S_UL_VX_UL_48_8K_ADDR                               1010
#define S_UL_VX_UL_48_8K_ADDR_END                           1021
#define S_UL_VX_UL_48_8K_sizeof                             12
#define S_UL_VX_UL_48_16K_ADDR                              1022
#define S_UL_VX_UL_48_16K_ADDR_END                          1033
#define S_UL_VX_UL_48_16K_sizeof                            12
#define S_UL_MIC_48K_ADDR                                   1034
#define S_UL_MIC_48K_ADDR_END                               1045
#define S_UL_MIC_48K_sizeof                                 12
#define S_Voice_8k_UL_ADDR                                  1046
#define S_Voice_8k_UL_ADDR_END                              1048
#define S_Voice_8k_UL_sizeof                                3
#define S_Voice_8k_DL_ADDR                                  1049
#define S_Voice_8k_DL_ADDR_END                              1050
#define S_Voice_8k_DL_sizeof                                2
#define S_McPDM_Out1_ADDR                                   1051
#define S_McPDM_Out1_ADDR_END                               1074
#define S_McPDM_Out1_sizeof                                 24
#define S_McPDM_Out2_ADDR                                   1075
#define S_McPDM_Out2_ADDR_END                               1098
#define S_McPDM_Out2_sizeof                                 24
#define S_McPDM_Out3_ADDR                                   1099
#define S_McPDM_Out3_ADDR_END                               1122
#define S_McPDM_Out3_sizeof                                 24
#define S_Voice_16k_UL_ADDR                                 1123
#define S_Voice_16k_UL_ADDR_END                             1127
#define S_Voice_16k_UL_sizeof                               5
#define S_Voice_16k_DL_ADDR                                 1128
#define S_Voice_16k_DL_ADDR_END                             1131
#define S_Voice_16k_DL_sizeof                               4
#define S_XinASRC_DL_VX_ADDR                                1132
#define S_XinASRC_DL_VX_ADDR_END                            1171
#define S_XinASRC_DL_VX_sizeof                              40
#define S_XinASRC_UL_VX_ADDR                                1172
#define S_XinASRC_UL_VX_ADDR_END                            1211
#define S_XinASRC_UL_VX_sizeof                              40
#define S_XinASRC_MM_EXT_IN_ADDR                            1212
#define S_XinASRC_MM_EXT_IN_ADDR_END                        1251
#define S_XinASRC_MM_EXT_IN_sizeof                          40
#define S_VX_REC_ADDR                                       1252
#define S_VX_REC_ADDR_END                                   1263
#define S_VX_REC_sizeof                                     12
#define S_VX_REC_L_ADDR                                     1264
#define S_VX_REC_L_ADDR_END                                 1275
#define S_VX_REC_L_sizeof                                   12
#define S_VX_REC_R_ADDR                                     1276
#define S_VX_REC_R_ADDR_END                                 1287
#define S_VX_REC_R_sizeof                                   12
#define S_DL2_M_L_ADDR                                      1288
#define S_DL2_M_L_ADDR_END                                  1299
#define S_DL2_M_L_sizeof                                    12
#define S_DL2_M_R_ADDR                                      1300
#define S_DL2_M_R_ADDR_END                                  1311
#define S_DL2_M_R_sizeof                                    12
#define S_DL2_M_LR_EQ_data_ADDR                             1312
#define S_DL2_M_LR_EQ_data_ADDR_END                         1336
#define S_DL2_M_LR_EQ_data_sizeof                           25
#define S_DL1_M_EQ_data_ADDR                                1337
#define S_DL1_M_EQ_data_ADDR_END                            1361
#define S_DL1_M_EQ_data_sizeof                              25
#define S_EARP_48_96_LP_data_ADDR                           1362
#define S_EARP_48_96_LP_data_ADDR_END                       1376
#define S_EARP_48_96_LP_data_sizeof                         15
#define S_IHF_48_96_LP_data_ADDR                            1377
#define S_IHF_48_96_LP_data_ADDR_END                        1391
#define S_IHF_48_96_LP_data_sizeof                          15
#define S_VX_UL_8_TEMP_ADDR                                 1392
#define S_VX_UL_8_TEMP_ADDR_END                             1393
#define S_VX_UL_8_TEMP_sizeof                               2
#define S_VX_UL_16_TEMP_ADDR                                1394
#define S_VX_UL_16_TEMP_ADDR_END                            1397
#define S_VX_UL_16_TEMP_sizeof                              4
#define S_VX_DL_8_48_LP_data_ADDR                           1398
#define S_VX_DL_8_48_LP_data_ADDR_END                       1408
#define S_VX_DL_8_48_LP_data_sizeof                         11
#define S_VX_DL_8_48_HP_data_ADDR                           1409
#define S_VX_DL_8_48_HP_data_ADDR_END                       1415
#define S_VX_DL_8_48_HP_data_sizeof                         7
#define S_VX_DL_16_48_LP_data_ADDR                          1416
#define S_VX_DL_16_48_LP_data_ADDR_END                      1426
#define S_VX_DL_16_48_LP_data_sizeof                        11
#define S_VX_DL_16_48_HP_data_ADDR                          1427
#define S_VX_DL_16_48_HP_data_ADDR_END                      1431
#define S_VX_DL_16_48_HP_data_sizeof                        5
#define S_VX_UL_48_8_LP_data_ADDR                           1432
#define S_VX_UL_48_8_LP_data_ADDR_END                       1442
#define S_VX_UL_48_8_LP_data_sizeof                         11
#define S_VX_UL_48_8_HP_data_ADDR                           1443
#define S_VX_UL_48_8_HP_data_ADDR_END                       1449
#define S_VX_UL_48_8_HP_data_sizeof                         7
#define S_VX_UL_48_16_LP_data_ADDR                          1450
#define S_VX_UL_48_16_LP_data_ADDR_END                      1460
#define S_VX_UL_48_16_LP_data_sizeof                        11
#define S_VX_UL_48_16_HP_data_ADDR                          1461
#define S_VX_UL_48_16_HP_data_ADDR_END                      1467
#define S_VX_UL_48_16_HP_data_sizeof                        7
#define S_BT_UL_8_48_LP_data_ADDR                           1468
#define S_BT_UL_8_48_LP_data_ADDR_END                       1478
#define S_BT_UL_8_48_LP_data_sizeof                         11
#define S_BT_UL_8_48_HP_data_ADDR                           1479
#define S_BT_UL_8_48_HP_data_ADDR_END                       1485
#define S_BT_UL_8_48_HP_data_sizeof                         7
#define S_BT_UL_16_48_LP_data_ADDR                          1486
#define S_BT_UL_16_48_LP_data_ADDR_END                      1496
#define S_BT_UL_16_48_LP_data_sizeof                        11
#define S_BT_UL_16_48_HP_data_ADDR                          1497
#define S_BT_UL_16_48_HP_data_ADDR_END                      1501
#define S_BT_UL_16_48_HP_data_sizeof                        5
#define S_BT_DL_48_8_LP_data_ADDR                           1502
#define S_BT_DL_48_8_LP_data_ADDR_END                       1512
#define S_BT_DL_48_8_LP_data_sizeof                         11
#define S_BT_DL_48_8_HP_data_ADDR                           1513
#define S_BT_DL_48_8_HP_data_ADDR_END                       1519
#define S_BT_DL_48_8_HP_data_sizeof                         7
#define S_BT_DL_48_16_LP_data_ADDR                          1520
#define S_BT_DL_48_16_LP_data_ADDR_END                      1530
#define S_BT_DL_48_16_LP_data_sizeof                        11
#define S_BT_DL_48_16_HP_data_ADDR                          1531
#define S_BT_DL_48_16_HP_data_ADDR_END                      1535
#define S_BT_DL_48_16_HP_data_sizeof                        5
#define S_ECHO_REF_48_8_LP_data_ADDR                        1536
#define S_ECHO_REF_48_8_LP_data_ADDR_END                    1546
#define S_ECHO_REF_48_8_LP_data_sizeof                      11
#define S_ECHO_REF_48_8_HP_data_ADDR                        1547
#define S_ECHO_REF_48_8_HP_data_ADDR_END                    1553
#define S_ECHO_REF_48_8_HP_data_sizeof                      7
#define S_ECHO_REF_48_16_LP_data_ADDR                       1554
#define S_ECHO_REF_48_16_LP_data_ADDR_END                   1564
#define S_ECHO_REF_48_16_LP_data_sizeof                     11
#define S_ECHO_REF_48_16_HP_data_ADDR                       1565
#define S_ECHO_REF_48_16_HP_data_ADDR_END                   1569
#define S_ECHO_REF_48_16_HP_data_sizeof                     5
#define S_APS_IIRmem1_ADDR                                  1570
#define S_APS_IIRmem1_ADDR_END                              1578
#define S_APS_IIRmem1_sizeof                                9
#define S_APS_M_IIRmem2_ADDR                                1579
#define S_APS_M_IIRmem2_ADDR_END                            1581
#define S_APS_M_IIRmem2_sizeof                              3
#define S_APS_C_IIRmem2_ADDR                                1582
#define S_APS_C_IIRmem2_ADDR_END                            1584
#define S_APS_C_IIRmem2_sizeof                              3
#define S_APS_DL1_OutSamples_ADDR                           1585
#define S_APS_DL1_OutSamples_ADDR_END                       1586
#define S_APS_DL1_OutSamples_sizeof                         2
#define S_APS_DL1_COIL_OutSamples_ADDR                      1587
#define S_APS_DL1_COIL_OutSamples_ADDR_END                  1588
#define S_APS_DL1_COIL_OutSamples_sizeof                    2
#define S_APS_DL2_L_OutSamples_ADDR                         1589
#define S_APS_DL2_L_OutSamples_ADDR_END                     1590
#define S_APS_DL2_L_OutSamples_sizeof                       2
#define S_APS_DL2_L_COIL_OutSamples_ADDR                    1591
#define S_APS_DL2_L_COIL_OutSamples_ADDR_END                1592
#define S_APS_DL2_L_COIL_OutSamples_sizeof                  2
#define S_APS_DL2_R_OutSamples_ADDR                         1593
#define S_APS_DL2_R_OutSamples_ADDR_END                     1594
#define S_APS_DL2_R_OutSamples_sizeof                       2
#define S_APS_DL2_R_COIL_OutSamples_ADDR                    1595
#define S_APS_DL2_R_COIL_OutSamples_ADDR_END                1596
#define S_APS_DL2_R_COIL_OutSamples_sizeof                  2
#define S_XinASRC_ECHO_REF_ADDR                             1597
#define S_XinASRC_ECHO_REF_ADDR_END                         1636
#define S_XinASRC_ECHO_REF_sizeof                           40
#define S_ECHO_REF_16K_ADDR                                 1637
#define S_ECHO_REF_16K_ADDR_END                             1641
#define S_ECHO_REF_16K_sizeof                               5
#define S_ECHO_REF_8K_ADDR                                  1642
#define S_ECHO_REF_8K_ADDR_END                              1644
#define S_ECHO_REF_8K_sizeof                                3
#define S_DL1_EQ_ADDR                                       1645
#define S_DL1_EQ_ADDR_END                                   1656
#define S_DL1_EQ_sizeof                                     12
#define S_DL2_EQ_ADDR                                       1657
#define S_DL2_EQ_ADDR_END                                   1668
#define S_DL2_EQ_sizeof                                     12
#define S_DL1_GAIN_out_ADDR                                 1669
#define S_DL1_GAIN_out_ADDR_END                             1680
#define S_DL1_GAIN_out_sizeof                               12
#define S_DL2_GAIN_out_ADDR                                 1681
#define S_DL2_GAIN_out_ADDR_END                             1692
#define S_DL2_GAIN_out_sizeof                               12
#define S_APS_DL2_L_IIRmem1_ADDR                            1693
#define S_APS_DL2_L_IIRmem1_ADDR_END                        1701
#define S_APS_DL2_L_IIRmem1_sizeof                          9
#define S_APS_DL2_R_IIRmem1_ADDR                            1702
#define S_APS_DL2_R_IIRmem1_ADDR_END                        1710
#define S_APS_DL2_R_IIRmem1_sizeof                          9
#define S_APS_DL2_L_M_IIRmem2_ADDR                          1711
#define S_APS_DL2_L_M_IIRmem2_ADDR_END                      1713
#define S_APS_DL2_L_M_IIRmem2_sizeof                        3
#define S_APS_DL2_R_M_IIRmem2_ADDR                          1714
#define S_APS_DL2_R_M_IIRmem2_ADDR_END                      1716
#define S_APS_DL2_R_M_IIRmem2_sizeof                        3
#define S_APS_DL2_L_C_IIRmem2_ADDR                          1717
#define S_APS_DL2_L_C_IIRmem2_ADDR_END                      1719
#define S_APS_DL2_L_C_IIRmem2_sizeof                        3
#define S_APS_DL2_R_C_IIRmem2_ADDR                          1720
#define S_APS_DL2_R_C_IIRmem2_ADDR_END                      1722
#define S_APS_DL2_R_C_IIRmem2_sizeof                        3
#define S_DL1_APS_ADDR                                      1723
#define S_DL1_APS_ADDR_END                                  1734
#define S_DL1_APS_sizeof                                    12
#define S_DL2_L_APS_ADDR                                    1735
#define S_DL2_L_APS_ADDR_END                                1746
#define S_DL2_L_APS_sizeof                                  12
#define S_DL2_R_APS_ADDR                                    1747
#define S_DL2_R_APS_ADDR_END                                1758
#define S_DL2_R_APS_sizeof                                  12
#define S_APS_DL1_EQ_data_ADDR                              1759
#define S_APS_DL1_EQ_data_ADDR_END                          1767
#define S_APS_DL1_EQ_data_sizeof                            9
#define S_APS_DL2_EQ_data_ADDR                              1768
#define S_APS_DL2_EQ_data_ADDR_END                          1776
#define S_APS_DL2_EQ_data_sizeof                            9
#define S_DC_DCvalue_ADDR                                   1777
#define S_DC_DCvalue_ADDR_END                               1777
#define S_DC_DCvalue_sizeof                                 1
#define S_VIBRA_ADDR                                        1778
#define S_VIBRA_ADDR_END                                    1783
#define S_VIBRA_sizeof                                      6
#define S_Vibra2_in_ADDR                                    1784
#define S_Vibra2_in_ADDR_END                                1789
#define S_Vibra2_in_sizeof                                  6
#define S_Vibra2_addr_ADDR                                  1790
#define S_Vibra2_addr_ADDR_END                              1790
#define S_Vibra2_addr_sizeof                                1
#define S_VibraCtrl_forRightSM_ADDR                         1791
#define S_VibraCtrl_forRightSM_ADDR_END                     1814
#define S_VibraCtrl_forRightSM_sizeof                       24
#define S_Rnoise_mem_ADDR                                   1815
#define S_Rnoise_mem_ADDR_END                               1815
#define S_Rnoise_mem_sizeof                                 1
#define S_Ctrl_ADDR                                         1816
#define S_Ctrl_ADDR_END                                     1833
#define S_Ctrl_sizeof                                       18
#define S_Vibra1_in_ADDR                                    1834
#define S_Vibra1_in_ADDR_END                                1839
#define S_Vibra1_in_sizeof                                  6
#define S_Vibra1_temp_ADDR                                  1840
#define S_Vibra1_temp_ADDR_END                              1863
#define S_Vibra1_temp_sizeof                                24
#define S_VibraCtrl_forLeftSM_ADDR                          1864
#define S_VibraCtrl_forLeftSM_ADDR_END                      1887
#define S_VibraCtrl_forLeftSM_sizeof                        24
#define S_Vibra1_mem_ADDR                                   1888
#define S_Vibra1_mem_ADDR_END                               1898
#define S_Vibra1_mem_sizeof                                 11
#define S_VibraCtrl_Stereo_ADDR                             1899
#define S_VibraCtrl_Stereo_ADDR_END                         1922
#define S_VibraCtrl_Stereo_sizeof                           24
#define S_AMIC_96_48_data_ADDR                              1923
#define S_AMIC_96_48_data_ADDR_END                          1941
#define S_AMIC_96_48_data_sizeof                            19
#define S_DMIC0_96_48_data_ADDR                             1942
#define S_DMIC0_96_48_data_ADDR_END                         1960
#define S_DMIC0_96_48_data_sizeof                           19
#define S_DMIC1_96_48_data_ADDR                             1961
#define S_DMIC1_96_48_data_ADDR_END                         1979
#define S_DMIC1_96_48_data_sizeof                           19
#define S_DMIC2_96_48_data_ADDR                             1980
#define S_DMIC2_96_48_data_ADDR_END                         1998
#define S_DMIC2_96_48_data_sizeof                           19
#define S_DBG_8K_PATTERN_ADDR                               1999
#define S_DBG_8K_PATTERN_ADDR_END                           2000
#define S_DBG_8K_PATTERN_sizeof                             2
#define S_DBG_16K_PATTERN_ADDR                              2001
#define S_DBG_16K_PATTERN_ADDR_END                          2004
#define S_DBG_16K_PATTERN_sizeof                            4
#define S_DBG_24K_PATTERN_ADDR                              2005
#define S_DBG_24K_PATTERN_ADDR_END                          2010
#define S_DBG_24K_PATTERN_sizeof                            6
#define S_DBG_48K_PATTERN_ADDR                              2011
#define S_DBG_48K_PATTERN_ADDR_END                          2022
#define S_DBG_48K_PATTERN_sizeof                            12
#define S_DBG_96K_PATTERN_ADDR                              2023
#define S_DBG_96K_PATTERN_ADDR_END                          2046
#define S_DBG_96K_PATTERN_sizeof                            24
#define S_MM_EXT_IN_ADDR                                    2047
#define S_MM_EXT_IN_ADDR_END                                2058
#define S_MM_EXT_IN_sizeof                                  12
#define S_MM_EXT_IN_L_ADDR                                  2059
#define S_MM_EXT_IN_L_ADDR_END                              2070
#define S_MM_EXT_IN_L_sizeof                                12
#define S_MM_EXT_IN_R_ADDR                                  2071
#define S_MM_EXT_IN_R_ADDR_END                              2082
#define S_MM_EXT_IN_R_sizeof                                12
#define S_MIC4_ADDR                                         2083
#define S_MIC4_ADDR_END                                     2094
#define S_MIC4_sizeof                                       12
#define S_MIC4_L_ADDR                                       2095
#define S_MIC4_L_ADDR_END                                   2106
#define S_MIC4_L_sizeof                                     12
#define S_MIC4_R_ADDR                                       2107
#define S_MIC4_R_ADDR_END                                   2118
#define S_MIC4_R_sizeof                                     12
#define S_HW_TEST_ADDR                                      2119
#define S_HW_TEST_ADDR_END                                  2119
#define S_HW_TEST_sizeof                                    1
#define S_XinASRC_BT_UL_ADDR                                2120
#define S_XinASRC_BT_UL_ADDR_END                            2159
#define S_XinASRC_BT_UL_sizeof                              40
#define S_XinASRC_BT_DL_ADDR                                2160
#define S_XinASRC_BT_DL_ADDR_END                            2199
#define S_XinASRC_BT_DL_sizeof                              40
#define S_BT_DL_8k_TEMP_ADDR                                2200
#define S_BT_DL_8k_TEMP_ADDR_END                            2201
#define S_BT_DL_8k_TEMP_sizeof                              2
#define S_BT_DL_16k_TEMP_ADDR                               2202
#define S_BT_DL_16k_TEMP_ADDR_END                           2205
#define S_BT_DL_16k_TEMP_sizeof                             4
#endif /* _ABESM_ADDR_H_ */
