snd-soc-abe-hal-objs +=  abe_addr.o \
			abe_aess.o \
			abe_asrc.o \
			abe_core.o \
			abe_dat.o \
			abe_dbg.o \
			abe_ini.o \
			abe_gain.o \
			abe_port.o \
			abe_seq.o \
			port_mgr.o \

obj-$(CONFIG_SND_OMAP_SOC_ABE) += snd-soc-abe-hal.o
