snd-soc-abe-hal-objs += abe_api.o \
			abe_aess.o \
			abe_dbg.o \
			abe_dat.o \
			abe_ext.o \
			abe_ini.o \
			abe_irq.o \
			abe_lib.o \
			abe_mem.o \
			abe_seq.o \

obj-$(CONFIG_SND_OMAP_SOC_ABE_DSP) += snd-soc-abe-hal.o
