/*
 * OMAP54xx Clock data
 *
 * Copyright (C) 2013 Texas Instruments, Inc.
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 * Mike Turquette (mturquette@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * XXX Some of the ES1 clocks have been removed/changed; once support
 * is added for discriminating clocks by ES level, these should be added back
 * in.
 */

#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/clk-private.h>
#include <linux/clkdev.h>
#include <linux/io.h>

#include "soc.h"
#include "iomap.h"
#include "clock.h"
#include "clock54xx.h"
#include "cm1_54xx.h"
#include "cm2_54xx.h"
#include "cm-regbits-54xx.h"
#include "prm54xx.h"
#include "prm-regbits-54xx.h"
#include "control.h"
#include "scrm54xx.h"

/* OMAP4 modulemode control */
#define OMAP54XX_MODULEMODE_HWCTRL		0
#define OMAP54XX_MODULEMODE_SWCTRL		1

/*
 * OMAP5 ABE DPLL default frequency. In OMAP5430 ES2.0 TRM version R, section
 * "3.6.3.2.3 CKGEN_ABE Clock Generator" states that the "DPLL_ABE_X2_CLK
 * must be set to 196.608 MHz" and hence, the DPLL locked frequency is
 * half of this value.
 */
#define OMAP5_DPLL_ABE_DEFFREQ				98304000

/*
 * OMAP543x TRM, section "3.6.3.9.5 DPLL_USB Preferred Settings"
 * states it must be at 960MHz
 */
#define OMAP5_DPLL_USB_DEFFREQ				960000000

/* Root clocks */

DEFINE_CLK_FIXED_RATE(pad_clks_src_ck, CLK_IS_ROOT, 12000000, 0x0);

DEFINE_CLK_GATE(pad_clks_ck, "pad_clks_src_ck", &pad_clks_src_ck, 0x0,
		OMAP54XX_CM_CLKSEL_ABE, OMAP54XX_PAD_CLKS_GATE_SHIFT, 0x0,
		NULL);

DEFINE_CLK_FIXED_RATE(secure_32k_clk_src_ck, CLK_IS_ROOT, 32768, 0x0);

DEFINE_CLK_FIXED_RATE(slimbus_src_clk, CLK_IS_ROOT, 12000000, 0x0);

DEFINE_CLK_GATE(slimbus_clk, "slimbus_src_clk", &slimbus_src_clk, 0x0,
		OMAP54XX_CM_CLKSEL_ABE, OMAP54XX_SLIMBUS1_CLK_GATE_SHIFT, 0x0,
		NULL);

DEFINE_CLK_FIXED_RATE(sys_32k_ck, CLK_IS_ROOT, 32768, 0x0);

DEFINE_CLK_FIXED_RATE(virt_12000000_ck, CLK_IS_ROOT, 12000000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_13000000_ck, CLK_IS_ROOT, 13000000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_16800000_ck, CLK_IS_ROOT, 16800000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_19200000_ck, CLK_IS_ROOT, 19200000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_26000000_ck, CLK_IS_ROOT, 26000000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_27000000_ck, CLK_IS_ROOT, 27000000, 0x0);

DEFINE_CLK_FIXED_RATE(virt_38400000_ck, CLK_IS_ROOT, 38400000, 0x0);


static const char *sys_clkin_parents[] = {
	"virt_12000000_ck", "virt_13000000_ck", "virt_16800000_ck",
	"virt_19200000_ck", "virt_26000000_ck", "virt_27000000_ck",
	"virt_38400000_ck",
};

DEFINE_CLK_MUX(sys_clkin, sys_clkin_parents, NULL, 0x0, OMAP54XX_CM_CLKSEL_SYS,
	       OMAP54XX_SYS_CLKSEL_SHIFT, OMAP54XX_SYS_CLKSEL_WIDTH,
	       CLK_MUX_INDEX_ONE, NULL);

DEFINE_CLK_FIXED_RATE(xclk60mhsp1_ck, CLK_IS_ROOT, 60000000, 0x0);

DEFINE_CLK_FIXED_RATE(xclk60mhsp2_ck, CLK_IS_ROOT, 60000000, 0x0);

/* Module clocks and DPLL outputs */

static const char *abe_dpll_bypass_clk_mux_parents[] = {
	"sys_clkin", "sys_32k_ck",
};

DEFINE_CLK_MUX(abe_dpll_bypass_clk_mux, abe_dpll_bypass_clk_mux_parents, NULL,
	       0x0, OMAP54XX_CM_CLKSEL_WKUPAON, OMAP54XX_CLKSEL_0_0_SHIFT,
	       OMAP54XX_CLKSEL_0_0_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(abe_dpll_clk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_CLKSEL_ABE_PLL_REF, OMAP54XX_CLKSEL_0_0_SHIFT,
	       OMAP54XX_CLKSEL_0_0_WIDTH, 0x0, NULL);

/* DPLL_ABE */
static struct dpll_data dpll_abe_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_ABE,
	.clk_bypass	= &abe_dpll_bypass_clk_mux,
	.clk_ref	= &abe_dpll_clk_mux,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_ABE,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_ABE,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_ABE,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.m4xen_mask	= OMAP54XX_DPLL_REGM4XEN_MASK,
	.lpmode_mask	= OMAP54XX_DPLL_LPMODE_EN_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};

static const char *dpll_abe_ck_parents[] = {
	"abe_dpll_clk_mux", "abe_dpll_bypass_clk_mux"
};

static struct clk dpll_abe_ck;

static const struct clk_ops dpll_abe_ck_ops = {
	.enable		= &omap3_noncore_dpll_enable,
	.disable	= &omap3_noncore_dpll_disable,
	.recalc_rate	= &omap4_dpll_regm4xen_recalc,
	.round_rate	= &omap4_dpll_regm4xen_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
	.get_parent	= &omap2_init_dpll_parent,
};

static struct clk_hw_omap dpll_abe_ck_hw = {
	.hw = {
		.clk = &dpll_abe_ck,
	},
	.dpll_data	= &dpll_abe_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_abe_ck, dpll_abe_ck_parents, dpll_abe_ck_ops);

static const char *dpll_abe_x2_ck_parents[] = {
	"dpll_abe_ck",
};

static struct clk dpll_abe_x2_ck;

static const struct clk_ops dpll_abe_x2_ck_ops = {
	.recalc_rate	= &omap3_clkoutx2_recalc,
};

static struct clk_hw_omap dpll_abe_x2_ck_hw = {
	.hw = {
		.clk = &dpll_abe_x2_ck,
	},
};

DEFINE_STRUCT_CLK(dpll_abe_x2_ck, dpll_abe_x2_ck_parents, dpll_abe_x2_ck_ops);

static const struct clk_ops omap_hsdivider_ops = {
	.set_rate	= &omap2_clksel_set_rate,
	.recalc_rate	= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
};

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_abe_m2x2_ck, "dpll_abe_x2_ck", &dpll_abe_x2_ck,
			    0x0, OMAP54XX_CM_DIV_M2_DPLL_ABE,
			    OMAP54XX_DIVHS_0_4_MASK);

DEFINE_CLK_FIXED_FACTOR(abe_24m_fclk, "dpll_abe_m2x2_ck", &dpll_abe_m2x2_ck,
			0x0, 1, 8);

DEFINE_CLK_DIVIDER(abe_clk, "dpll_abe_m2x2_ck", &dpll_abe_m2x2_ck, 0x0,
		   OMAP54XX_CM_CLKSEL_ABE, OMAP54XX_CLKSEL_OPP_SHIFT,
		   OMAP54XX_CLKSEL_OPP_WIDTH, CLK_DIVIDER_POWER_OF_TWO, NULL);

DEFINE_CLK_FIXED_FACTOR(abe_iclk, "abe_clk", &abe_clk, 0x0, 1, 2);

DEFINE_CLK_FIXED_FACTOR(abe_lp_clk_div, "dpll_abe_m2x2_ck", &dpll_abe_m2x2_ck,
			0x0, 1, 16);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_abe_m3x2_ck, "dpll_abe_x2_ck", &dpll_abe_x2_ck,
			    0x0, OMAP54XX_CM_DIV_M3_DPLL_ABE,
			    OMAP54XX_DIVHS_0_4_MASK);

/* DPLL_CORE */
static struct dpll_data dpll_core_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_CORE,
	.clk_bypass	= &dpll_abe_m3x2_ck,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_CORE,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_CORE,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_CORE,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};

static const char *dpll_core_ck_parents[] = {
	"sys_clkin", "dpll_abe_m3x2_ck"
};

static struct clk dpll_core_ck;

static const struct clk_ops dpll_core_ck_ops = {
	.recalc_rate	= &omap3_dpll_recalc,
	.get_parent	= &omap2_init_dpll_parent,
};

static struct clk_hw_omap dpll_core_ck_hw = {
	.hw = {
		.clk = &dpll_core_ck,
	},
	.dpll_data	= &dpll_core_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_core_ck, dpll_core_ck_parents, dpll_core_ck_ops);

static const char *dpll_core_x2_ck_parents[] = {
	"dpll_core_ck",
};

static struct clk dpll_core_x2_ck;

static struct clk_hw_omap dpll_core_x2_ck_hw = {
	.hw = {
		.clk = &dpll_core_x2_ck,
	},
};

DEFINE_STRUCT_CLK(dpll_core_x2_ck, dpll_core_x2_ck_parents, dpll_abe_x2_ck_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h21x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H21_DPLL_CORE, OMAP54XX_DIVHS_MASK);

static const char *c2c_fclk_parents[] = {
	"dpll_core_h21x2_ck",
};

static struct clk c2c_fclk;

static const struct clk_ops c2c_fclk_ops = {
};

static struct clk_hw_omap c2c_fclk_hw = {
	.hw = {
		.clk = &c2c_fclk,
	},
};

DEFINE_STRUCT_CLK(c2c_fclk, c2c_fclk_parents, c2c_fclk_ops);

DEFINE_CLK_FIXED_FACTOR(c2c_iclk, "c2c_fclk", &c2c_fclk, 0x0, 1, 2);

DEFINE_CLK_FIXED_FACTOR(custefuse_sys_gfclk_div, "sys_clkin", &sys_clkin, 0x0,
			1, 2);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h11x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H11_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h12x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H12_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h13x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H13_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h14x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H14_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h22x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H22_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h23x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H23_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_h24x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0,
			    OMAP54XX_CM_DIV_H24_DPLL_CORE, OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_m2_ck, "dpll_core_ck", &dpll_core_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_CORE,
			    OMAP54XX_DIVHS_0_4_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_core_m3x2_ck, "dpll_core_x2_ck",
			    &dpll_core_x2_ck, 0x0, OMAP54XX_CM_DIV_M3_DPLL_CORE,
			    OMAP54XX_DIVHS_0_4_MASK);

static const char *iva_dpll_hs_clk_div_parents[] = {
	"dpll_core_h12x2_ck",
};

static struct clk iva_dpll_hs_clk_div;

static struct clk_hw_omap iva_dpll_hs_clk_div_hw = {
	.hw = {
		.clk = &iva_dpll_hs_clk_div,
	},
};

DEFINE_STRUCT_CLK(iva_dpll_hs_clk_div, iva_dpll_hs_clk_div_parents,
		  c2c_fclk_ops);

/* DPLL_IVA */
static struct dpll_data dpll_iva_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_IVA,
	.clk_bypass	= &iva_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_IVA,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_IVA,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_IVA,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};

static const char *dpll_iva_ck_parents[] = {
	"sys_clkin", "iva_dpll_hs_clk_div"
};

static struct clk dpll_iva_ck;

static const struct clk_ops dpll_iva_ck_ops = {
	.enable		= &omap3_noncore_dpll_enable,
	.disable	= &omap3_noncore_dpll_disable,
	.recalc_rate	= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
	.get_parent	= &omap2_init_dpll_parent,
};

static struct clk_hw_omap dpll_iva_ck_hw = {
	.hw = {
		.clk = &dpll_iva_ck,
	},
	.dpll_data	= &dpll_iva_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_iva_ck, dpll_iva_ck_parents, dpll_iva_ck_ops);

static const char *dpll_iva_x2_ck_parents[] = {
	"dpll_iva_ck",
};

static struct clk dpll_iva_x2_ck;

static struct clk_hw_omap dpll_iva_x2_ck_hw = {
	.hw = {
		.clk = &dpll_iva_x2_ck,
	},
};

DEFINE_STRUCT_CLK(dpll_iva_x2_ck, dpll_iva_x2_ck_parents, dpll_abe_x2_ck_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_iva_h11x2_ck, "dpll_iva_x2_ck",
			    &dpll_iva_x2_ck, 0x0, OMAP54XX_CM_DIV_H11_DPLL_IVA,
			    OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_iva_h12x2_ck, "dpll_iva_x2_ck",
			    &dpll_iva_x2_ck, 0x0, OMAP54XX_CM_DIV_H12_DPLL_IVA,
			    OMAP54XX_DIVHS_MASK);

static struct clk mpu_dpll_hs_clk_div;

static struct clk_hw_omap mpu_dpll_hs_clk_div_hw = {
	.hw = {
		.clk = &mpu_dpll_hs_clk_div,
	},
};

DEFINE_STRUCT_CLK(mpu_dpll_hs_clk_div, iva_dpll_hs_clk_div_parents,
		  c2c_fclk_ops);

/* DPLL_MPU */
static struct dpll_data dpll_mpu_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_MPU,
	.clk_bypass	= &mpu_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_MPU,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_MPU,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_MPU,
	.dcc_mask       = OMAP54XX_DCC_EN_MASK,
	/* rate bigger than 1.4 GHz will use DCC */
	.dcc_rate       = 1400000000,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};

static const char *dpll_mpu_ck_parents[] = {
	"sys_clkin", "mpu_dpll_hs_clk_div"
};

static struct clk dpll_mpu_ck;

static const struct clk_ops dpll_mpu_ck_ops = {
	.enable		= &omap3_noncore_dpll_enable,
	.disable	= &omap3_noncore_dpll_disable,
	.recalc_rate	= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap5_mpu_dpll_set_rate,
	.get_parent	= &omap2_init_dpll_parent,
};

static struct clk_hw_omap dpll_mpu_ck_hw = {
	.hw = {
		.clk = &dpll_mpu_ck,
	},
	.dpll_data	= &dpll_mpu_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_mpu_ck, dpll_mpu_ck_parents, dpll_mpu_ck_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_mpu_m2_ck, "dpll_mpu_ck", &dpll_mpu_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_MPU,
			    OMAP54XX_DIVHS_0_4_MASK);

DEFINE_CLK_FIXED_FACTOR(per_dpll_hs_clk_div, "dpll_abe_m3x2_ck",
			&dpll_abe_m3x2_ck, 0x0, 1, 2);

/* DPLL_PER */
static struct dpll_data dpll_per_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_PER,
	.clk_bypass	= &per_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_PER,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_PER,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_PER,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};

static const char *dpll_per_ck_parents[] = {
	"sys_clkin", "per_dpll_hs_clk_div"
};

static struct clk dpll_per_ck;

static struct clk_hw_omap dpll_per_ck_hw = {
	.hw = {
		.clk = &dpll_per_ck,
	},
	.dpll_data	= &dpll_per_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_per_ck, dpll_per_ck_parents, dpll_iva_ck_ops);

static const char *dpll_per_x2_ck_parents[] = {
	"dpll_per_ck",
};

static struct clk dpll_per_x2_ck;

static struct clk_hw_omap dpll_per_x2_ck_hw = {
	.hw = {
		.clk = &dpll_per_x2_ck,
	},
};

DEFINE_STRUCT_CLK(dpll_per_x2_ck, dpll_per_x2_ck_parents, dpll_abe_x2_ck_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_h11x2_ck, "dpll_per_x2_ck",
			    &dpll_per_x2_ck, 0x0, OMAP54XX_CM_DIV_H11_DPLL_PER,
			    OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_h12x2_ck, "dpll_per_x2_ck",
			    &dpll_per_x2_ck, 0x0, OMAP54XX_CM_DIV_H12_DPLL_PER,
			    OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_h14x2_ck, "dpll_per_x2_ck",
			    &dpll_per_x2_ck, 0x0, OMAP54XX_CM_DIV_H14_DPLL_PER,
			    OMAP54XX_DIVHS_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_m2_ck, "dpll_per_ck", &dpll_per_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_PER,
			    OMAP54XX_DIVHS_0_4_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_m2x2_ck, "dpll_per_x2_ck", &dpll_per_x2_ck,
			    0x0, OMAP54XX_CM_DIV_M2_DPLL_PER,
			    OMAP54XX_DIVHS_0_4_MASK);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_per_m3x2_ck, "dpll_per_x2_ck", &dpll_per_x2_ck,
			    0x0, OMAP54XX_CM_DIV_M3_DPLL_PER,
			    OMAP54XX_DIVHS_0_4_MASK);

/* DPLL_UNIPRO1 */
static struct dpll_data dpll_unipro1_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_UNIPRO1,
	.clk_bypass	= &sys_clkin,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_UNIPRO1,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_UNIPRO1,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_UNIPRO1,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};

static const char *dpll_unipro1_ck_parents[] = {
	"sys_clkin",
};

static struct clk dpll_unipro1_ck;

static struct clk_hw_omap dpll_unipro1_ck_hw = {
	.hw = {
		.clk = &dpll_unipro1_ck,
	},
	.dpll_data	= &dpll_unipro1_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_unipro1_ck, dpll_unipro1_ck_parents, dpll_iva_ck_ops);

static const char *dpll_unipro1_clkdcoldo_parents[] = {
	"dpll_unipro1_ck",
};

static struct clk dpll_unipro1_clkdcoldo;

static struct clk_hw_omap dpll_unipro1_clkdcoldo_hw = {
	.hw = {
		.clk = &dpll_unipro1_clkdcoldo,
	},
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_UNIPRO1,
};

DEFINE_STRUCT_CLK(dpll_unipro1_clkdcoldo, dpll_unipro1_clkdcoldo_parents,
		  c2c_fclk_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_unipro1_m2_ck, "dpll_unipro1_ck",
			    &dpll_unipro1_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_UNIPRO1,
			    OMAP54XX_DIVHS_0_6_MASK);

/* DPLL_UNIPRO2 */
static struct dpll_data dpll_unipro2_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_UNIPRO2,
	.clk_bypass	= &sys_clkin,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_UNIPRO2,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_UNIPRO2,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_UNIPRO2,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};

static struct clk dpll_unipro2_ck;

static struct clk_hw_omap dpll_unipro2_ck_hw = {
	.hw = {
		.clk = &dpll_unipro2_ck,
	},
	.dpll_data	= &dpll_unipro2_dd,
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_unipro2_ck, dpll_unipro1_ck_parents, dpll_iva_ck_ops);

static const char *dpll_unipro2_clkdcoldo_parents[] = {
	"dpll_unipro2_ck",
};

static struct clk dpll_unipro2_clkdcoldo;

static struct clk_hw_omap dpll_unipro2_clkdcoldo_hw = {
	.hw = {
		.clk = &dpll_unipro2_clkdcoldo,
	},
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_UNIPRO2,
};

DEFINE_STRUCT_CLK(dpll_unipro2_clkdcoldo, dpll_unipro2_clkdcoldo_parents,
		  c2c_fclk_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_unipro2_m2_ck, "dpll_unipro2_ck",
			    &dpll_unipro2_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_UNIPRO2,
			    OMAP54XX_DIVHS_0_6_MASK);

DEFINE_CLK_FIXED_FACTOR(usb_dpll_hs_clk_div, "dpll_abe_m3x2_ck",
			&dpll_abe_m3x2_ck, 0x0, 1, 3);

/* DPLL_USB */
static struct dpll_data dpll_usb_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_USB,
	.clk_bypass	= &usb_dpll_hs_clk_div,
	.flags		= DPLL_J_TYPE,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_USB,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_USB,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_USB,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.sddiv_mask	= OMAP54XX_DPLL_SD_DIV_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};

static const char *dpll_usb_ck_parents[] = {
	"sys_clkin", "usb_dpll_hs_clk_div"
};

static struct clk dpll_usb_ck;

static const struct clk_ops dpll_usb_ck_ops = {
	.enable		= &omap3_noncore_dpll_enable,
	.disable	= &omap3_noncore_dpll_disable,
	.recalc_rate	= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
	.get_parent	= &omap2_init_dpll_parent,
	.init	= &omap2_init_clk_clkdm,
};

static struct clk_hw_omap dpll_usb_ck_hw = {
	.hw = {
		.clk = &dpll_usb_ck,
	},
	.dpll_data	= &dpll_usb_dd,
	.clkdm_name	= "l3init_clkdm",
	.ops		= &clkhwops_omap3_dpll,
};

DEFINE_STRUCT_CLK(dpll_usb_ck, dpll_usb_ck_parents, dpll_usb_ck_ops);

static const char *dpll_usb_clkdcoldo_parents[] = {
	"dpll_usb_ck",
};

static struct clk dpll_usb_clkdcoldo;

static struct clk_hw_omap dpll_usb_clkdcoldo_hw = {
	.hw = {
		.clk = &dpll_usb_clkdcoldo,
	},
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_USB,
};

DEFINE_STRUCT_CLK(dpll_usb_clkdcoldo, dpll_usb_clkdcoldo_parents, c2c_fclk_ops);

DEFINE_CLK_OMAP_HSDIVIDER63(dpll_usb_m2_ck, "dpll_usb_ck", &dpll_usb_ck, 0x0,
			    OMAP54XX_CM_DIV_M2_DPLL_USB,
			    OMAP54XX_DIVHS_0_6_MASK);

static const char *dss_syc_gfclk_div_parents[] = {
	"sys_clkin",
};

static struct clk dss_syc_gfclk_div;

static struct clk_hw_omap dss_syc_gfclk_div_hw = {
	.hw = {
		.clk = &dss_syc_gfclk_div,
	},
};

DEFINE_STRUCT_CLK(dss_syc_gfclk_div, dss_syc_gfclk_div_parents, c2c_fclk_ops);

DEFINE_CLK_FIXED_FACTOR(func_128m_clk, "dpll_per_h11x2_ck", &dpll_per_h11x2_ck,
			0x0, 1, 2);

DEFINE_CLK_FIXED_FACTOR(func_12m_fclk, "dpll_per_m2x2_ck", &dpll_per_m2x2_ck,
			0x0, 1, 16);

DEFINE_CLK_FIXED_FACTOR(func_24m_clk, "dpll_per_m2_ck", &dpll_per_m2_ck, 0x0, 1,
			4);

DEFINE_CLK_FIXED_FACTOR(func_48m_fclk, "dpll_per_m2x2_ck", &dpll_per_m2x2_ck,
			0x0, 1, 4);

DEFINE_CLK_FIXED_FACTOR(func_96m_fclk, "dpll_per_m2x2_ck", &dpll_per_m2x2_ck,
			0x0, 1, 2);

static struct clk l3_iclk_div;

static struct clk_hw_omap l3_iclk_div_hw = {
	.hw = {
		.clk = &l3_iclk_div,
	},
};

DEFINE_STRUCT_CLK(l3_iclk_div, iva_dpll_hs_clk_div_parents, c2c_fclk_ops);

static const char *gpu_l3_iclk_parents[] = {
	"l3_iclk_div",
};

static struct clk gpu_l3_iclk;

static struct clk_hw_omap gpu_l3_iclk_hw = {
	.hw = {
		.clk = &gpu_l3_iclk,
	},
};

DEFINE_STRUCT_CLK(gpu_l3_iclk, gpu_l3_iclk_parents, c2c_fclk_ops);

static const struct clk_div_table l3init_60m_fclk_rates[] = {
	{ .div = 1, .val = 0 },
	{ .div = 8, .val = 1 },
	{ .div = 0 },
};
DEFINE_CLK_DIVIDER_TABLE(l3init_60m_fclk, "dpll_usb_m2_ck", &dpll_usb_m2_ck,
			 0x0, OMAP54XX_CM_CLKSEL_USB_60MHZ,
			 OMAP54XX_CLKSEL_0_0_SHIFT, OMAP54XX_CLKSEL_0_0_WIDTH,
			 0x0, l3init_60m_fclk_rates, NULL);

static const char *wkupaon_iclk_mux_parents[] = {
	"sys_clkin", "abe_lp_clk_div",
};

DEFINE_CLK_MUX(wkupaon_iclk_mux, wkupaon_iclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_CLKSEL_WKUPAON, OMAP54XX_CLKSEL_0_0_SHIFT,
	       OMAP54XX_CLKSEL_0_0_WIDTH, 0x0, NULL);

static const char *l3instr_ts_gclk_div_parents[] = {
	"wkupaon_iclk_mux",
};

static struct clk l3instr_ts_gclk_div;

static struct clk_hw_omap l3instr_ts_gclk_div_hw = {
	.hw = {
		.clk = &l3instr_ts_gclk_div,
	},
};

DEFINE_STRUCT_CLK(l3instr_ts_gclk_div, l3instr_ts_gclk_div_parents,
		  c2c_fclk_ops);

static struct clk l4_root_clk_div;

static struct clk_hw_omap l4_root_clk_div_hw = {
	.hw = {
		.clk = &l4_root_clk_div,
	},
};

DEFINE_STRUCT_CLK(l4_root_clk_div, gpu_l3_iclk_parents, c2c_fclk_ops);

/* Leaf clocks controlled by modules */

DEFINE_CLK_GATE(dss_32khz_clk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_DSS_DSS_CLKCTRL, OMAP54XX_OPTFCLKEN_32KHZ_CLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(dss_48mhz_clk, "func_48m_fclk", &func_48m_fclk, 0x0,
		OMAP54XX_CM_DSS_DSS_CLKCTRL, OMAP54XX_OPTFCLKEN_48MHZ_CLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(dss_dss_clk, "dpll_per_h12x2_ck", &dpll_per_h12x2_ck, 0x0,
		OMAP54XX_CM_DSS_DSS_CLKCTRL, OMAP54XX_OPTFCLKEN_DSSCLK_SHIFT,
		0x0, NULL);

static const struct clk_ops dss_sys_clk_ops = {
	.enable		= &omap2_dflt_clk_enable,
	.disable	= &omap2_dflt_clk_disable,
	.is_enabled	= &omap2_dflt_clk_is_enabled,
	.init	= &omap2_init_clk_clkdm,
};

static const char *dss_sys_clk_parents[] = {
	"dss_syc_gfclk_div",
};

static struct clk dss_sys_clk;

static struct clk_hw_omap dss_sys_clk_hw = {
	.hw = {
		.clk = &dss_sys_clk,
	},
	.clkdm_name	= "dss_clkdm",
	.enable_reg	= OMAP54XX_CM_DSS_DSS_CLKCTRL,
	.enable_bit	= OMAP54XX_OPTFCLKEN_SYS_CLK_SHIFT,
};

DEFINE_STRUCT_CLK(dss_sys_clk, dss_sys_clk_parents, dss_sys_clk_ops);

DEFINE_CLK_GATE(gpio1_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_WKUPAON_GPIO1_CLKCTRL,
		OMAP54XX_OPTFCLKEN_DBCLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(gpio2_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO2_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio3_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO3_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio4_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO4_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio5_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO5_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio6_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO6_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio7_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO7_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(gpio8_dbclk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L4PER_GPIO8_CLKCTRL, OMAP54XX_OPTFCLKEN_DBCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(iss_ctrlclk, "func_96m_fclk", &func_96m_fclk, 0x0,
		OMAP54XX_CM_CAM_ISS_CLKCTRL, OMAP54XX_OPTFCLKEN_CTRLCLK_SHIFT,
		0x0, NULL);

DEFINE_CLK_GATE(lli_txphy_clk, "dpll_unipro1_clkdcoldo",
		&dpll_unipro1_clkdcoldo, 0x0, OMAP54XX_CM_MIPIEXT_LLI_CLKCTRL,
		OMAP54XX_OPTFCLKEN_TXPHY_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(lli_txphy_ls_clk, "dpll_unipro1_m2_ck", &dpll_unipro1_m2_ck,
		0x0, OMAP54XX_CM_MIPIEXT_LLI_CLKCTRL,
		OMAP54XX_OPTFCLKEN_TXPHY_LS_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(mmc1_32khz_clk, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_L3INIT_MMC1_CLKCTRL,
		OMAP54XX_OPTFCLKEN_32KHZ_CLK_8_8_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(sata_ref_clk, "sys_clkin", &sys_clkin, 0x0,
		OMAP54XX_CM_L3INIT_SATA_CLKCTRL,
		OMAP54XX_OPTFCLKEN_REF_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(slimbus1_slimbus_clk, "slimbus_clk", &slimbus_clk, 0x0,
		OMAP54XX_CM_ABE_SLIMBUS1_CLKCTRL,
		OMAP54XX_OPTFCLKEN_SLIMBUS_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic480m_p1_clk, "dpll_usb_m2_ck", &dpll_usb_m2_ck,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC480M_P1_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic480m_p2_clk, "dpll_usb_m2_ck", &dpll_usb_m2_ck,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC480M_P2_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic480m_p3_clk, "dpll_usb_m2_ck", &dpll_usb_m2_ck,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC480M_P3_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic60m_p1_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC60M_P1_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic60m_p2_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC60M_P2_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_hsic60m_p3_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_HSIC60M_P3_CLK_SHIFT, 0x0, NULL);

static const char *utmi_p1_gfclk_parents[] = {
	"l3init_60m_fclk", "xclk60mhsp1",
};

DEFINE_CLK_MUX(utmi_p1_gfclk, utmi_p1_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
	       OMAP54XX_CLKSEL_UTMI_P1_SHIFT, OMAP54XX_CLKSEL_UTMI_P1_WIDTH,
	       0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_utmi_p1_clk, "utmi_p1_gfclk", &utmi_p1_gfclk, 0x0,
		OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_UTMI_P1_CLK_SHIFT, 0x0, NULL);

static const char *utmi_p2_gfclk_parents[] = {
	"l3init_60m_fclk", "xclk60mhsp2",
};

DEFINE_CLK_MUX(utmi_p2_gfclk, utmi_p2_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
	       OMAP54XX_CLKSEL_UTMI_P2_SHIFT, OMAP54XX_CLKSEL_UTMI_P2_WIDTH,
	       0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_utmi_p2_clk, "utmi_p2_gfclk", &utmi_p2_gfclk, 0x0,
		OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_UTMI_P2_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_host_hs_utmi_p3_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_UTMI_P3_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_otg_ss_refclk960m, "dpll_usb_clkdcoldo",
		&dpll_usb_clkdcoldo, 0x0, OMAP54XX_CM_L3INIT_USB_OTG_SS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_REFCLK960M_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_phy_cm_clk32k, "sys_32k_ck", &sys_32k_ck, 0x0,
		OMAP54XX_CM_COREAON_USB_PHY_CORE_CLKCTRL,
		OMAP54XX_OPTFCLKEN_CLK32K_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_tll_hs_usb_ch0_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_TLL_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_USB_CH0_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_tll_hs_usb_ch1_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_TLL_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_USB_CH1_CLK_SHIFT, 0x0, NULL);

DEFINE_CLK_GATE(usb_tll_hs_usb_ch2_clk, "l3init_60m_fclk", &l3init_60m_fclk,
		0x0, OMAP54XX_CM_L3INIT_USB_TLL_HS_CLKCTRL,
		OMAP54XX_OPTFCLKEN_USB_CH2_CLK_SHIFT, 0x0, NULL);

/* Remaining optional clocks */
DEFINE_CLK_DIVIDER(aess_fclk, "abe_clk", &abe_clk, 0x0,
		   OMAP54XX_CM_ABE_AESS_CLKCTRL,
		   OMAP54XX_CLKSEL_AESS_FCLK_SHIFT,
		   OMAP54XX_CLKSEL_AESS_FCLK_WIDTH, 0x0, NULL);

static const char *dmic_sync_mux_ck_parents[] = {
	"abe_24m_fclk", "dss_syc_gfclk_div", "func_24m_clk",
};

DEFINE_CLK_MUX(dmic_sync_mux_ck, dmic_sync_mux_ck_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_DMIC_CLKCTRL,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_WIDTH, 0x0, NULL);

static const char *dmic_gfclk_parents[] = {
	"dmic_sync_mux_ck", "pad_clks", "slimbus_clk",
};

DEFINE_CLK_MUX(dmic_gfclk, dmic_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_DMIC_CLKCTRL, OMAP54XX_CLKSEL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_WIDTH, 0x0, NULL);

DEFINE_CLK_DIVIDER(fdif_fclk, "dpll_per_h11x2_ck", &dpll_per_h11x2_ck, 0x0,
		   OMAP54XX_CM_CAM_FDIF_CLKCTRL, OMAP54XX_CLKSEL_FCLK_SHIFT,
		   OMAP54XX_CLKSEL_FCLK_WIDTH, 0x0, NULL);

static const char *gpu_core_gclk_mux_parents[] = {
	"dpll_core_h14x2_ck", "dpll_per_h14x2_ck",
};

DEFINE_CLK_MUX(gpu_core_gclk_mux, gpu_core_gclk_mux_parents, NULL,
	       CLK_SET_RATE_PARENT, OMAP54XX_CM_GPU_GPU_CLKCTRL,
	       OMAP54XX_CLKSEL_GPU_CORE_GCLK_SHIFT,
	       OMAP54XX_CLKSEL_GPU_CORE_GCLK_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(gpu_hyd_gclk_mux, gpu_core_gclk_mux_parents, NULL,
	       CLK_SET_RATE_PARENT, OMAP54XX_CM_GPU_GPU_CLKCTRL,
	       OMAP54XX_CLKSEL_GPU_HYD_GCLK_SHIFT,
	       OMAP54XX_CLKSEL_GPU_HYD_GCLK_WIDTH, 0x0, NULL);

DEFINE_CLK_DIVIDER(hsi_fclk, "dpll_per_m2x2_ck", &dpll_per_m2x2_ck, 0x0,
		   OMAP54XX_CM_L3INIT_HSI_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
		   OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(mcasp_sync_mux_ck, dmic_sync_mux_ck_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCASP_CLKCTRL,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_WIDTH, 0x0, NULL);

static const char *mcasp_gfclk_parents[] = {
	"mcasp_sync_mux_ck", "pad_clks", "slimbus_clk",
};

DEFINE_CLK_MUX(mcasp_gfclk, mcasp_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCASP_CLKCTRL, OMAP54XX_CLKSEL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(mcbsp1_sync_mux_ck, dmic_sync_mux_ck_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP1_CLKCTRL,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_WIDTH, 0x0, NULL);

static const char *mcbsp1_gfclk_parents[] = {
	"mcbsp1_sync_mux_ck", "pad_clks", "slimbus_clk",
};

DEFINE_CLK_MUX(mcbsp1_gfclk, mcbsp1_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP1_CLKCTRL, OMAP54XX_CLKSEL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(mcbsp2_sync_mux_ck, dmic_sync_mux_ck_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP2_CLKCTRL,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_WIDTH, 0x0, NULL);

static const char *mcbsp2_gfclk_parents[] = {
	"mcbsp2_sync_mux_ck", "pad_clks", "slimbus_clk",
};

DEFINE_CLK_MUX(mcbsp2_gfclk, mcbsp2_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP2_CLKCTRL, OMAP54XX_CLKSEL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(mcbsp3_sync_mux_ck, dmic_sync_mux_ck_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP3_CLKCTRL,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_INTERNAL_SOURCE_WIDTH, 0x0, NULL);

static const char *mcbsp3_gfclk_parents[] = {
	"mcbsp3_sync_mux_ck", "pad_clks", "slimbus_clk",
};

DEFINE_CLK_MUX(mcbsp3_gfclk, mcbsp3_gfclk_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_MCBSP3_CLKCTRL, OMAP54XX_CLKSEL_SOURCE_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_WIDTH, 0x0, NULL);

static const char *mmc1_fclk_mux_parents[] = {
	"func_128m_clk", "dpll_per_m2x2_ck",
};

DEFINE_CLK_MUX(mmc1_fclk_mux, mmc1_fclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L3INIT_MMC1_CLKCTRL,
	       OMAP54XX_CLKSEL_SOURCE_L3INIT_MMC1_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_L3INIT_MMC1_WIDTH, 0x0, NULL);

DEFINE_CLK_DIVIDER(mmc1_fclk, "mmc1_fclk_mux", &mmc1_fclk_mux, 0x0,
		   OMAP54XX_CM_L3INIT_MMC1_CLKCTRL, OMAP54XX_CLKSEL_DIV_SHIFT,
		   OMAP54XX_CLKSEL_DIV_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(mmc2_fclk_mux, mmc1_fclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L3INIT_MMC2_CLKCTRL,
	       OMAP54XX_CLKSEL_SOURCE_L3INIT_MMC1_SHIFT,
	       OMAP54XX_CLKSEL_SOURCE_L3INIT_MMC1_WIDTH, 0x0, NULL);

DEFINE_CLK_DIVIDER(mmc2_fclk, "mmc2_fclk_mux", &mmc2_fclk_mux, 0x0,
		   OMAP54XX_CM_L3INIT_MMC2_CLKCTRL, OMAP54XX_CLKSEL_DIV_SHIFT,
		   OMAP54XX_CLKSEL_DIV_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer10_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER10_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer11_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER11_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer1_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_WKUPAON_TIMER1_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer2_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER2_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer3_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER3_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer4_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER4_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

static const char *timer5_gfclk_mux_parents[] = {
	"dss_syc_gfclk_div", "sys_32k_ck",
};

DEFINE_CLK_MUX(timer5_gfclk_mux, timer5_gfclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_TIMER5_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer6_gfclk_mux, timer5_gfclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_TIMER6_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer7_gfclk_mux, timer5_gfclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_TIMER7_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer8_gfclk_mux, timer5_gfclk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_ABE_TIMER8_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

DEFINE_CLK_MUX(timer9_gfclk_mux, abe_dpll_bypass_clk_mux_parents, NULL, 0x0,
	       OMAP54XX_CM_L4PER_TIMER9_CLKCTRL, OMAP54XX_CLKSEL_SHIFT,
	       OMAP54XX_CLKSEL_WIDTH, 0x0, NULL);

/* SCRM aux clk nodes */
static const char *dpll_core_m3x2_opt_ck_parents[] = {
	"dpll_core_m3x2_ck",
};

static struct clk dpll_core_m3x2_opt_ck;

static struct clk_hw_omap dpll_core_m3x2_opt_ck_hw = {
	.hw = {
		.clk = &dpll_core_m3x2_opt_ck,
	},
	.clkdm_name	= "wkupaon_clkdm",
	.enable_reg	= OMAP54XX_CM_WKUPAON_SCRM_CLKCTRL,
	.enable_bit	= OMAP54XX_OPTFCLKEN_SCRM_CORE_SHIFT,
};

DEFINE_STRUCT_CLK(dpll_core_m3x2_opt_ck, dpll_core_m3x2_opt_ck_parents,
		  dss_sys_clk_ops);

static const char *dpll_per_m3x2_opt_ck_parents[] = {
	"dpll_per_m3x2_ck",
};

static struct clk dpll_per_m3x2_opt_ck;

static struct clk_hw_omap dpll_per_m3x2_opt_ck_hw = {
	.hw = {
		.clk = &dpll_per_m3x2_opt_ck,
	},
	.clkdm_name	= "wkupaon_clkdm",
	.enable_reg	= OMAP54XX_CM_WKUPAON_SCRM_CLKCTRL,
	.enable_bit	= OMAP54XX_OPTFCLKEN_SCRM_PER_SHIFT,
};

DEFINE_STRUCT_CLK(dpll_per_m3x2_opt_ck, dpll_per_m3x2_opt_ck_parents,
		  dss_sys_clk_ops);

static const struct clksel auxclk_src_sel[] = {
	{ .parent = &sys_clkin, .rates = div_1_0_rates },
	{ .parent = &dpll_core_m3x2_opt_ck, .rates = div_1_1_rates },
	{ .parent = &dpll_per_m3x2_opt_ck, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static const char *auxclk_src_ck_parents[] = {
	"sys_clkin_ck", "dpll_core_m3x2_ck", "dpll_per_m3x2_ck",
};

static const struct clk_ops auxclk_src_ck_ops = {
	.enable		= &omap2_dflt_clk_enable,
	.disable	= &omap2_dflt_clk_disable,
	.is_enabled	= &omap2_dflt_clk_is_enabled,
	.recalc_rate	= &omap2_clksel_recalc,
	.get_parent	= &omap2_clksel_find_parent_index,
};

DEFINE_CLK_OMAP_MUX_GATE(auxclk0_src_ck, NULL, auxclk_src_sel,
			 OMAP5_SCRM_AUXCLK0, OMAP5_SRCSELECT_MASK,
			 OMAP5_SCRM_AUXCLK0, OMAP5_ENABLE_SHIFT, NULL,
			 auxclk_src_ck_parents, auxclk_src_ck_ops);

DEFINE_CLK_DIVIDER(auxclk0_ck, "auxclk0_src_ck", &auxclk0_src_ck, 0x0,
		   OMAP5_SCRM_AUXCLK0, OMAP5_CLKDIV_SHIFT, OMAP5_CLKDIV_WIDTH,
		   0x0, NULL);

DEFINE_CLK_OMAP_MUX_GATE(auxclk1_src_ck, NULL, auxclk_src_sel,
			 OMAP5_SCRM_AUXCLK1, OMAP5_SRCSELECT_MASK,
			 OMAP5_SCRM_AUXCLK1, OMAP5_ENABLE_SHIFT, NULL,
			 auxclk_src_ck_parents, auxclk_src_ck_ops);

DEFINE_CLK_DIVIDER(auxclk1_ck, "auxclk1_src_ck", &auxclk1_src_ck, 0x0,
		   OMAP5_SCRM_AUXCLK1, OMAP5_CLKDIV_SHIFT, OMAP5_CLKDIV_WIDTH,
		   0x0, NULL);

DEFINE_CLK_OMAP_MUX_GATE(auxclk2_src_ck, NULL, auxclk_src_sel,
			 OMAP5_SCRM_AUXCLK2, OMAP5_SRCSELECT_MASK,
			 OMAP5_SCRM_AUXCLK2, OMAP5_ENABLE_SHIFT, NULL,
			 auxclk_src_ck_parents, auxclk_src_ck_ops);

DEFINE_CLK_DIVIDER(auxclk2_ck, "auxclk2_src_ck", &auxclk2_src_ck, 0x0,
		   OMAP5_SCRM_AUXCLK2, OMAP5_CLKDIV_SHIFT, OMAP5_CLKDIV_WIDTH,
		   0x0, NULL);

DEFINE_CLK_OMAP_MUX_GATE(auxclk3_src_ck, NULL, auxclk_src_sel,
			 OMAP5_SCRM_AUXCLK3, OMAP5_SRCSELECT_MASK,
			 OMAP5_SCRM_AUXCLK3, OMAP5_ENABLE_SHIFT, NULL,
			 auxclk_src_ck_parents, auxclk_src_ck_ops);

DEFINE_CLK_DIVIDER(auxclk3_ck, "auxclk3_src_ck", &auxclk3_src_ck, 0x0,
		   OMAP5_SCRM_AUXCLK3, OMAP5_CLKDIV_SHIFT, OMAP5_CLKDIV_WIDTH,
		   0x0, NULL);

static const char *auxclkreq_ck_parents[] = {
	"auxclk0_ck", "auxclk1_ck", "auxclk2_ck", "auxclk3_ck", "auxclk4_ck",
	"auxclk5_ck",
};

DEFINE_CLK_MUX(auxclkreq0_ck, auxclkreq_ck_parents, NULL, 0x0,
	       OMAP5_SCRM_AUXCLKREQ0, OMAP5_MAPPING_SHIFT, OMAP5_MAPPING_WIDTH,
	       0x0, NULL);

DEFINE_CLK_MUX(auxclkreq1_ck, auxclkreq_ck_parents, NULL, 0x0,
	       OMAP5_SCRM_AUXCLKREQ1, OMAP5_MAPPING_SHIFT, OMAP5_MAPPING_WIDTH,
	       0x0, NULL);

DEFINE_CLK_MUX(auxclkreq2_ck, auxclkreq_ck_parents, NULL, 0x0,
	       OMAP5_SCRM_AUXCLKREQ2, OMAP5_MAPPING_SHIFT, OMAP5_MAPPING_WIDTH,
	       0x0, NULL);

DEFINE_CLK_MUX(auxclkreq3_ck, auxclkreq_ck_parents, NULL, 0x0,
	       OMAP5_SCRM_AUXCLKREQ3, OMAP5_MAPPING_SHIFT, OMAP5_MAPPING_WIDTH,
	       0x0, NULL);

/*
 * clkdev
 */

static struct omap_clk omap54xx_clks[] = {
	CLK(NULL,	"pad_clks_src_ck",		&pad_clks_src_ck,	CK_54XX),
	CLK(NULL,	"pad_clks_ck",			&pad_clks_ck,	CK_54XX),
	CLK(NULL,	"secure_32k_clk_src_ck",	&secure_32k_clk_src_ck,	CK_54XX),
	CLK(NULL,	"slimbus_src_clk",		&slimbus_src_clk,	CK_54XX),
	CLK(NULL,	"slimbus_clk",			&slimbus_clk,	CK_54XX),
	CLK(NULL,	"sys_32k_ck",			&sys_32k_ck,	CK_54XX),
	CLK(NULL,	"virt_12000000_ck",		&virt_12000000_ck,	CK_54XX),
	CLK(NULL,	"virt_13000000_ck",		&virt_13000000_ck,	CK_54XX),
	CLK(NULL,	"virt_16800000_ck",		&virt_16800000_ck,	CK_54XX),
	CLK(NULL,	"virt_19200000_ck",		&virt_19200000_ck,	CK_54XX),
	CLK(NULL,	"virt_26000000_ck",		&virt_26000000_ck,	CK_54XX),
	CLK(NULL,	"virt_27000000_ck",		&virt_27000000_ck,	CK_54XX),
	CLK(NULL,	"virt_38400000_ck",		&virt_38400000_ck,	CK_54XX),
	CLK(NULL,	"sys_clkin",			&sys_clkin,	CK_54XX),
	CLK(NULL,	"xclk60mhsp1_ck",		&xclk60mhsp1_ck,	CK_54XX),
	CLK(NULL,	"xclk60mhsp2_ck",		&xclk60mhsp2_ck,	CK_54XX),
	CLK(NULL,	"abe_dpll_bypass_clk_mux",	&abe_dpll_bypass_clk_mux,	CK_54XX),
	CLK(NULL,	"abe_dpll_clk_mux",		&abe_dpll_clk_mux,	CK_54XX),
	CLK(NULL,	"dpll_abe_ck",			&dpll_abe_ck,	CK_54XX),
	CLK(NULL,	"dpll_abe_x2_ck",		&dpll_abe_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_abe_m2x2_ck",		&dpll_abe_m2x2_ck,	CK_54XX),
	CLK(NULL,	"abe_24m_fclk",			&abe_24m_fclk,	CK_54XX),
	CLK(NULL,	"abe_clk",			&abe_clk,	CK_54XX),
	CLK(NULL,	"abe_iclk",			&abe_iclk,	CK_54XX),
	CLK(NULL,	"abe_lp_clk_div",		&abe_lp_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_abe_m3x2_ck",		&dpll_abe_m3x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_ck",			&dpll_core_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_x2_ck",		&dpll_core_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h21x2_ck",		&dpll_core_h21x2_ck,	CK_54XX),
	CLK(NULL,	"c2c_fclk",			&c2c_fclk,	CK_54XX),
	CLK(NULL,	"c2c_iclk",			&c2c_iclk,	CK_54XX),
	CLK(NULL,	"custefuse_sys_gfclk_div",	&custefuse_sys_gfclk_div,	CK_54XX),
	CLK(NULL,	"dpll_core_h11x2_ck",		&dpll_core_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h12x2_ck",		&dpll_core_h12x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h13x2_ck",		&dpll_core_h13x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h14x2_ck",		&dpll_core_h14x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h22x2_ck",		&dpll_core_h22x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h23x2_ck",		&dpll_core_h23x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h24x2_ck",		&dpll_core_h24x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_m2_ck",		&dpll_core_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_m3x2_ck",		&dpll_core_m3x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_m3x2_opt_ck",	&dpll_core_m3x2_opt_ck,	CK_54XX),
	CLK(NULL,	"iva_dpll_hs_clk_div",		&iva_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_iva_ck",			&dpll_iva_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_x2_ck",		&dpll_iva_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_h11x2_ck",		&dpll_iva_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_h12x2_ck",		&dpll_iva_h12x2_ck,	CK_54XX),
	CLK(NULL,	"mpu_dpll_hs_clk_div",		&mpu_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_mpu_ck",			&dpll_mpu_ck,	CK_54XX),
	CLK(NULL,	"dpll_mpu_m2_ck",		&dpll_mpu_m2_ck,	CK_54XX),
	CLK(NULL,	"per_dpll_hs_clk_div",		&per_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_per_ck",			&dpll_per_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_x2_ck",		&dpll_per_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h11x2_ck",		&dpll_per_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h12x2_ck",		&dpll_per_h12x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h14x2_ck",		&dpll_per_h14x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m2_ck",		&dpll_per_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m2x2_ck",		&dpll_per_m2x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m3x2_opt_ck",		&dpll_per_m3x2_opt_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_ck",		&dpll_unipro1_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_clkdcoldo",	&dpll_unipro1_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_m2_ck",		&dpll_unipro1_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_ck",		&dpll_unipro2_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_clkdcoldo",	&dpll_unipro2_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_m2_ck",		&dpll_unipro2_m2_ck,	CK_54XX),
	CLK(NULL,	"usb_dpll_hs_clk_div",		&usb_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_usb_ck",			&dpll_usb_ck,	CK_54XX),
	CLK(NULL,	"dpll_usb_clkdcoldo",		&dpll_usb_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_usb_m2_ck",		&dpll_usb_m2_ck,	CK_54XX),
	CLK(NULL,	"dss_syc_gfclk_div",		&dss_syc_gfclk_div,	CK_54XX),
	CLK(NULL,	"func_128m_clk",		&func_128m_clk,	CK_54XX),
	CLK(NULL,	"func_12m_fclk",		&func_12m_fclk,	CK_54XX),
	CLK(NULL,	"func_24m_clk",			&func_24m_clk,	CK_54XX),
	CLK(NULL,	"func_48m_fclk",		&func_48m_fclk,	CK_54XX),
	CLK(NULL,	"func_96m_fclk",		&func_96m_fclk,	CK_54XX),
	CLK(NULL,	"l3_iclk_div",			&l3_iclk_div,	CK_54XX),
	CLK(NULL,	"gpu_l3_iclk",			&gpu_l3_iclk,	CK_54XX),
	CLK(NULL,	"l3init_60m_fclk",		&l3init_60m_fclk,	CK_54XX),
	CLK(NULL,	"init_60m_fclk",		&l3init_60m_fclk,	CK_54XX),
	CLK(NULL,	"wkupaon_iclk_mux",		&wkupaon_iclk_mux,	CK_54XX),
	CLK(NULL,	"l3instr_ts_gclk_div",		&l3instr_ts_gclk_div,	CK_54XX),
	CLK(NULL,	"l4_root_clk_div",		&l4_root_clk_div,	CK_54XX),
	CLK(NULL,	"dss_32khz_clk",		&dss_32khz_clk,	CK_54XX),
	CLK(NULL,	"dss_48mhz_clk",		&dss_48mhz_clk,	CK_54XX),
	CLK(NULL,	"dss_dss_clk",			&dss_dss_clk,	CK_54XX),
	CLK(NULL,	"dss_sys_clk",			&dss_sys_clk,	CK_54XX),
	CLK(NULL,	"gpio1_dbclk",			&gpio1_dbclk,	CK_54XX),
	CLK(NULL,	"gpio2_dbclk",			&gpio2_dbclk,	CK_54XX),
	CLK(NULL,	"gpio3_dbclk",			&gpio3_dbclk,	CK_54XX),
	CLK(NULL,	"gpio4_dbclk",			&gpio4_dbclk,	CK_54XX),
	CLK(NULL,	"gpio5_dbclk",			&gpio5_dbclk,	CK_54XX),
	CLK(NULL,	"gpio6_dbclk",			&gpio6_dbclk,	CK_54XX),
	CLK(NULL,	"gpio7_dbclk",			&gpio7_dbclk,	CK_54XX),
	CLK(NULL,	"gpio8_dbclk",			&gpio8_dbclk,	CK_54XX),
	CLK(NULL,	"iss_ctrlclk",			&iss_ctrlclk,	CK_54XX),
	CLK(NULL,	"lli_txphy_clk",		&lli_txphy_clk,	CK_54XX),
	CLK(NULL,	"lli_txphy_ls_clk",		&lli_txphy_ls_clk,	CK_54XX),
	CLK(NULL,	"mmc1_32khz_clk",		&mmc1_32khz_clk,	CK_54XX),
	CLK(NULL,	"sata_ref_clk",			&sata_ref_clk,	CK_54XX),
	CLK(NULL,	"slimbus1_slimbus_clk",		&slimbus1_slimbus_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic480m_p1_clk",	&usb_host_hs_hsic480m_p1_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic480m_p2_clk",	&usb_host_hs_hsic480m_p2_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic480m_p3_clk",	&usb_host_hs_hsic480m_p3_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic60m_p1_clk",	&usb_host_hs_hsic60m_p1_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic60m_p2_clk",	&usb_host_hs_hsic60m_p2_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_hsic60m_p3_clk",	&usb_host_hs_hsic60m_p3_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_utmi_p1_clk",	&usb_host_hs_utmi_p1_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_utmi_p2_clk",	&usb_host_hs_utmi_p2_clk,	CK_54XX),
	CLK(NULL,	"usb_host_hs_utmi_p3_clk",	&usb_host_hs_utmi_p3_clk,	CK_54XX),
	CLK(NULL,	"usb_otg_ss_refclk960m",	&usb_otg_ss_refclk960m,	CK_54XX),
	CLK(NULL,	"usb_phy_cm_clk32k",		&usb_phy_cm_clk32k,	CK_54XX),
	CLK(NULL,	"usb_tll_hs_usb_ch0_clk",	&usb_tll_hs_usb_ch0_clk,	CK_54XX),
	CLK(NULL,	"usb_tll_hs_usb_ch1_clk",	&usb_tll_hs_usb_ch1_clk,	CK_54XX),
	CLK(NULL,	"usb_tll_hs_usb_ch2_clk",	&usb_tll_hs_usb_ch2_clk,	CK_54XX),
	CLK(NULL,	"aess_fclk",			&aess_fclk,	CK_54XX),
	CLK(NULL,	"dmic_sync_mux_ck",		&dmic_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"dmic_gfclk",			&dmic_gfclk,	CK_54XX),
	CLK(NULL,	"fdif_fclk",			&fdif_fclk,	CK_54XX),
	CLK(NULL,	"gpu_core_gclk_mux",		&gpu_core_gclk_mux,	CK_54XX),
	CLK(NULL,	"gpu_hyd_gclk_mux",		&gpu_hyd_gclk_mux,	CK_54XX),
	CLK(NULL,	"hsi_fclk",			&hsi_fclk,	CK_54XX),
	CLK(NULL,	"mcasp_sync_mux_ck",		&mcasp_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcasp_gfclk",			&mcasp_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp1_sync_mux_ck",		&mcbsp1_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp1_gfclk",			&mcbsp1_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp2_sync_mux_ck",		&mcbsp2_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp2_gfclk",			&mcbsp2_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp3_sync_mux_ck",		&mcbsp3_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp3_gfclk",			&mcbsp3_gfclk,	CK_54XX),
	CLK(NULL,	"mmc1_fclk_mux",		&mmc1_fclk_mux,	CK_54XX),
	CLK(NULL,	"mmc1_fclk",			&mmc1_fclk,	CK_54XX),
	CLK(NULL,	"mmc2_fclk_mux",		&mmc2_fclk_mux,	CK_54XX),
	CLK(NULL,	"mmc2_fclk",			&mmc2_fclk,	CK_54XX),
	CLK(NULL,	"timer10_gfclk_mux",		&timer10_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer11_gfclk_mux",		&timer11_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer1_gfclk_mux",		&timer1_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer2_gfclk_mux",		&timer2_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer3_gfclk_mux",		&timer3_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer4_gfclk_mux",		&timer4_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer5_gfclk_mux",		&timer5_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer6_gfclk_mux",		&timer6_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer7_gfclk_mux",		&timer7_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer8_gfclk_mux",		&timer8_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer9_gfclk_mux",		&timer9_gfclk_mux,	CK_54XX),
	CLK(NULL,	"utmi_p1_gfclk",		&utmi_p1_gfclk,	CK_54XX),
	CLK(NULL,	"utmi_p2_gfclk",		&utmi_p2_gfclk,	CK_54XX),
	CLK(NULL,	"auxclk0_src_ck",		&auxclk0_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk0_ck",			&auxclk0_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq0_ck",		&auxclkreq0_ck,	CK_54XX),
	CLK(NULL,	"auxclk1_src_ck",		&auxclk1_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk1_ck",			&auxclk1_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq1_ck",		&auxclkreq1_ck,	CK_54XX),
	CLK(NULL,	"auxclk2_src_ck",		&auxclk2_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk2_ck",			&auxclk2_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq2_ck",		&auxclkreq2_ck,	CK_54XX),
	CLK(NULL,	"auxclk3_src_ck",		&auxclk3_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk3_ck",			&auxclk3_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq3_ck",		&auxclkreq3_ck,	CK_54XX),
	CLK(NULL,	"gpmc_ck",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"mailboxes_ick",		&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.0",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart1_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart2_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart3_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart4_ick",			&dummy_ck,	CK_54XX),
	CLK("usbhs_omap",	"usbhost_ick",		&dummy_ck,	CK_54XX),
	CLK("usbhs_omap",	"usbtll_fck",		&dummy_ck,	CK_54XX),
	CLK("omap_wdt",	"ick",				&dummy_ck,	CK_54XX),
	CLK(NULL,	"timer_32k_ck",			&sys_32k_ck, 	CK_54XX),
	CLK("4ae18000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("48032000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("48034000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("48036000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("4803e000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("48086000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("48088000.timer",	"timer_sys_ck",		&sys_clkin, 	CK_54XX),
	CLK("40138000.timer",	"timer_sys_ck",		&dss_syc_gfclk_div, 	CK_54XX),
	CLK("4013a000.timer",	"timer_sys_ck",		&dss_syc_gfclk_div, 	CK_54XX),
	CLK("4013c000.timer",	"timer_sys_ck",		&dss_syc_gfclk_div, 	CK_54XX),
	CLK("4013e000.timer",	"timer_sys_ck",		&dss_syc_gfclk_div, 	CK_54XX),
};

static struct reparent_init_clks reparent_clks[] = {
	{ .name = "abe_dpll_clk_mux", .parent = "sys_clkin" }
};

static struct rate_init_clks rate_clks[] = {
	{ .name = "dpll_usb_ck", .rate = OMAP5_DPLL_USB_DEFFREQ },
	{ .name = "dpll_usb_m2_ck", .rate = OMAP5_DPLL_USB_DEFFREQ/2 },
	{ .name = "dpll_abe_ck", .rate = OMAP5_DPLL_ABE_DEFFREQ },
	{ .name = "dpll_abe_m2x2_ck", .rate = OMAP5_DPLL_ABE_DEFFREQ * 2 },
};

int __init omap5xxx_clk_init(void)
{
	u32 cpu_clkflg;
	struct omap_clk *c;

	if (soc_is_omap54xx()) {
		cpu_mask = RATE_IN_54XX;
		cpu_clkflg = CK_54XX;
	}

	/*
	 * Must stay commented until all OMAP SoC drivers are
	 * converted to runtime PM, or drivers may start crashing
	 *
	 * omap2_clk_disable_clkdm_control();
	 */

	for (c = omap54xx_clks; c < omap54xx_clks + ARRAY_SIZE(omap54xx_clks);
									c++) {
		if (c->cpu & cpu_clkflg) {
			clkdev_add(&c->lk);
			if (!__clk_init(NULL, c->lk.clk))
				omap2_init_clk_hw_omap_clocks(c->lk.clk);
		}
	}

	omap2_clk_disable_autoidle_all();
	omap2_clk_reparent_init_clocks(reparent_clks, ARRAY_SIZE(reparent_clks));
	omap2_clk_rate_init_clocks(rate_clks, ARRAY_SIZE(rate_clks));

	return 0;
}
