/*
 * OMAP54xx Clock data
 *
 * Copyright (C) 2009-2012 Texas Instruments, Inc.
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * XXX Some of the ES1 clocks have been removed/changed; once support
 * is added for discriminating clocks by ES level, these should be added back
 * in.
 */

#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/clk.h>
#include <linux/io.h>

#include <plat/hardware.h>
#include <plat/clkdev_omap.h>

#include "iomap.h"
#include "clock.h"
#include "clock54xx.h"
#include "cm1_54xx.h"
#include "cm2_54xx.h"
#include "cm-regbits-54xx.h"
#include "prm54xx.h"
#include "prm-regbits-54xx.h"
#include "control.h"
#include "scrm54xx.h"

/* OMAP4 modulemode control */
#define OMAP54XX_MODULEMODE_HWCTRL			0
#define OMAP54XX_MODULEMODE_SWCTRL			1

/* Root clocks */

static struct clk pad_clks = {
	.name		= "pad_clks",
	.rate		= 12000000,
	.ops		= &clkops_omap2_dflt,
	.enable_reg	= OMAP54XX_CM_CLKSEL_ABE,
	.enable_bit	= OMAP54XX_PAD_CLKS_GATE_SHIFT,
};

static struct clk secure_32k_clk_src = {
	.name		= "secure_32k_clk_src",
	.rate		= 32768,
	.ops		= &clkops_null,
};

static struct clk slimbus_clk = {
	.name		= "slimbus_clk",
	.rate		= 12000000,
	.ops		= &clkops_omap2_dflt,
	.enable_reg	= OMAP54XX_CM_CLKSEL_ABE,
	.enable_bit	= OMAP54XX_SLIMBUS1_CLK_GATE_SHIFT,
};

static struct clk sys_32k_ck = {
	.name		= "sys_32k_ck",
	.rate		= 32768,
	.ops		= &clkops_null,
};

static struct clk virt_12000000_ck = {
	.name		= "virt_12000000_ck",
	.ops		= &clkops_null,
	.rate		= 12000000,
};

static struct clk virt_13000000_ck = {
	.name		= "virt_13000000_ck",
	.ops		= &clkops_null,
	.rate		= 13000000,
};

static struct clk virt_16800000_ck = {
	.name		= "virt_16800000_ck",
	.ops		= &clkops_null,
	.rate		= 16800000,
};

static struct clk virt_19200000_ck = {
	.name		= "virt_19200000_ck",
	.ops		= &clkops_null,
	.rate		= 19200000,
};

static struct clk virt_26000000_ck = {
	.name		= "virt_26000000_ck",
	.ops		= &clkops_null,
	.rate		= 26000000,
};

static struct clk virt_27000000_ck = {
	.name		= "virt_27000000_ck",
	.ops		= &clkops_null,
	.rate		= 27000000,
};

static struct clk virt_38400000_ck = {
	.name		= "virt_38400000_ck",
	.ops		= &clkops_null,
	.rate		= 38400000,
};

static const struct clksel_rate div_1_0_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_1_rates[] = {
	{ .div = 1, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_2_rates[] = {
	{ .div = 1, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_3_rates[] = {
	{ .div = 1, .val = 3, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_4_rates[] = {
	{ .div = 1, .val = 4, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_5_rates[] = {
	{ .div = 1, .val = 5, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_6_rates[] = {
	{ .div = 1, .val = 6, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel_rate div_1_7_rates[] = {
	{ .div = 1, .val = 7, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel sys_clkin_sel[] = {
	{ .parent = &virt_12000000_ck, .rates = div_1_1_rates },
	{ .parent = &virt_13000000_ck, .rates = div_1_2_rates },
	{ .parent = &virt_16800000_ck, .rates = div_1_3_rates },
	{ .parent = &virt_19200000_ck, .rates = div_1_4_rates },
	{ .parent = &virt_26000000_ck, .rates = div_1_5_rates },
	{ .parent = &virt_27000000_ck, .rates = div_1_6_rates },
	{ .parent = &virt_38400000_ck, .rates = div_1_7_rates },
	{ .parent = NULL },
};

static struct clk sys_clkin = {
	.name		= "sys_clkin",
	.rate		= 38400000,
	.clksel		= sys_clkin_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_CLKSEL_SYS,
	.clksel_mask	= OMAP54XX_SYS_CLKSEL_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk xclk60mhsp1 = {
	.name		= "xclk60mhsp1",
	.rate		= 60000000,
	.ops		= &clkops_null,
};

static struct clk xclk60mhsp2 = {
	.name		= "xclk60mhsp2",
	.rate		= 60000000,
	.ops		= &clkops_null,
};

/* Module clocks and DPLL outputs */

static const struct clksel abe_dpll_bypass_clk_mux_sel[] = {
	{ .parent = &sys_clkin, .rates = div_1_0_rates },
	{ .parent = &sys_32k_ck, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk abe_dpll_bypass_clk_mux = {
	.name		= "abe_dpll_bypass_clk_mux",
	.parent		= &sys_clkin,
	.clksel		= abe_dpll_bypass_clk_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_CLKSEL_WKUPAON,
	.clksel_mask	= OMAP54XX_CLKSEL_0_0_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk abe_dpll_clk_mux = {
	.name		= "abe_dpll_clk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

/* DPLL_ABE */
static struct dpll_data dpll_abe_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_ABE,
	.clk_bypass	= &abe_dpll_bypass_clk_mux,
	.clk_ref	= &abe_dpll_clk_mux,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_ABE,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_ABE,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_ABE,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};


static struct clk dpll_abe_ck = {
	.name		= "dpll_abe_ck",
	.parent		= &abe_dpll_clk_mux,
	.dpll_data	= &dpll_abe_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap4_dpll_regm4xen_recalc,
	.round_rate	= &omap4_dpll_regm4xen_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static struct clk dpll_abe_x2_ck = {
	.name		= "dpll_abe_x2_ck",
	.parent		= &dpll_abe_ck,
	.flags		= CLOCK_CLKOUTX2,
	.ops		= &clkops_null,
	.recalc		= &omap3_clkoutx2_recalc,
};

static const struct clksel_rate div31_1to31_rates[] = {
	{ .div = 1, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 3, .val = 3, .flags = RATE_IN_54XX },
	{ .div = 4, .val = 4, .flags = RATE_IN_54XX },
	{ .div = 5, .val = 5, .flags = RATE_IN_54XX },
	{ .div = 6, .val = 6, .flags = RATE_IN_54XX },
	{ .div = 7, .val = 7, .flags = RATE_IN_54XX },
	{ .div = 8, .val = 8, .flags = RATE_IN_54XX },
	{ .div = 9, .val = 9, .flags = RATE_IN_54XX },
	{ .div = 10, .val = 10, .flags = RATE_IN_54XX },
	{ .div = 11, .val = 11, .flags = RATE_IN_54XX },
	{ .div = 12, .val = 12, .flags = RATE_IN_54XX },
	{ .div = 13, .val = 13, .flags = RATE_IN_54XX },
	{ .div = 14, .val = 14, .flags = RATE_IN_54XX },
	{ .div = 15, .val = 15, .flags = RATE_IN_54XX },
	{ .div = 16, .val = 16, .flags = RATE_IN_54XX },
	{ .div = 17, .val = 17, .flags = RATE_IN_54XX },
	{ .div = 18, .val = 18, .flags = RATE_IN_54XX },
	{ .div = 19, .val = 19, .flags = RATE_IN_54XX },
	{ .div = 20, .val = 20, .flags = RATE_IN_54XX },
	{ .div = 21, .val = 21, .flags = RATE_IN_54XX },
	{ .div = 22, .val = 22, .flags = RATE_IN_54XX },
	{ .div = 23, .val = 23, .flags = RATE_IN_54XX },
	{ .div = 24, .val = 24, .flags = RATE_IN_54XX },
	{ .div = 25, .val = 25, .flags = RATE_IN_54XX },
	{ .div = 26, .val = 26, .flags = RATE_IN_54XX },
	{ .div = 27, .val = 27, .flags = RATE_IN_54XX },
	{ .div = 28, .val = 28, .flags = RATE_IN_54XX },
	{ .div = 29, .val = 29, .flags = RATE_IN_54XX },
	{ .div = 30, .val = 30, .flags = RATE_IN_54XX },
	{ .div = 31, .val = 31, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel dpll_abe_m2x2_div[] = {
	{ .parent = &dpll_abe_x2_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_abe_m2x2_ck = {
	.name		= "dpll_abe_m2x2_ck",
	.parent		= &dpll_abe_x2_ck,
	.clksel		= dpll_abe_m2x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_ABE,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk abe_24m_fclk = {
	.name		= "abe_24m_fclk",
	.parent		= &dpll_abe_m2x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 8,
	.recalc		= &omap_fixed_divisor_recalc,
};

static const struct clksel_rate div3_1to4_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 4, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel abe_clk_div[] = {
	{ .parent = &dpll_abe_m2x2_ck, .rates = div3_1to4_rates },
	{ .parent = NULL },
};

static struct clk abe_clk = {
	.name		= "abe_clk",
	.parent		= &dpll_abe_m2x2_ck,
	.clksel		= abe_clk_div,
	.clksel_reg	= OMAP54XX_CM_CLKSEL_ABE,
	.clksel_mask	= OMAP54XX_CLKSEL_OPP_0_1_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk abe_iclk = {
	.name		= "abe_iclk",
	.parent		= &abe_clk,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk abe_lp_clk_div = {
	.name		= "abe_lp_clk_div",
	.parent		= &dpll_abe_m2x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 16,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk dpll_abe_m3x2_ck = {
	.name		= "dpll_abe_m3x2_ck",
	.parent		= &dpll_abe_x2_ck,
	.clksel		= dpll_abe_m2x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M3_DPLL_ABE,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

/* DPLL_CORE */
static struct dpll_data dpll_core_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_CORE,
	.clk_bypass	= &dpll_abe_m3x2_ck,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_CORE,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_CORE,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_CORE,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};


static struct clk dpll_core_ck = {
	.name		= "dpll_core_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_core_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_core_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
};

static struct clk dpll_core_x2_ck = {
	.name		= "dpll_core_x2_ck",
	.parent		= &dpll_core_ck,
	.flags		= CLOCK_CLKOUTX2,
	.ops		= &clkops_null,
	.recalc		= &omap3_clkoutx2_recalc,
};

static const struct clksel_rate div63_1to63_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 3, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 4, .val = 3, .flags = RATE_IN_54XX },
	{ .div = 5, .val = 4, .flags = RATE_IN_54XX },
	{ .div = 6, .val = 5, .flags = RATE_IN_54XX },
	{ .div = 7, .val = 6, .flags = RATE_IN_54XX },
	{ .div = 8, .val = 7, .flags = RATE_IN_54XX },
	{ .div = 9, .val = 8, .flags = RATE_IN_54XX },
	{ .div = 10, .val = 9, .flags = RATE_IN_54XX },
	{ .div = 11, .val = 10, .flags = RATE_IN_54XX },
	{ .div = 12, .val = 11, .flags = RATE_IN_54XX },
	{ .div = 13, .val = 12, .flags = RATE_IN_54XX },
	{ .div = 14, .val = 13, .flags = RATE_IN_54XX },
	{ .div = 15, .val = 14, .flags = RATE_IN_54XX },
	{ .div = 16, .val = 15, .flags = RATE_IN_54XX },
	{ .div = 17, .val = 16, .flags = RATE_IN_54XX },
	{ .div = 18, .val = 17, .flags = RATE_IN_54XX },
	{ .div = 19, .val = 18, .flags = RATE_IN_54XX },
	{ .div = 20, .val = 19, .flags = RATE_IN_54XX },
	{ .div = 21, .val = 20, .flags = RATE_IN_54XX },
	{ .div = 22, .val = 21, .flags = RATE_IN_54XX },
	{ .div = 23, .val = 22, .flags = RATE_IN_54XX },
	{ .div = 24, .val = 23, .flags = RATE_IN_54XX },
	{ .div = 25, .val = 24, .flags = RATE_IN_54XX },
	{ .div = 26, .val = 25, .flags = RATE_IN_54XX },
	{ .div = 27, .val = 26, .flags = RATE_IN_54XX },
	{ .div = 28, .val = 27, .flags = RATE_IN_54XX },
	{ .div = 29, .val = 28, .flags = RATE_IN_54XX },
	{ .div = 30, .val = 29, .flags = RATE_IN_54XX },
	{ .div = 31, .val = 30, .flags = RATE_IN_54XX },
	{ .div = 32, .val = 31, .flags = RATE_IN_54XX },
	{ .div = 33, .val = 32, .flags = RATE_IN_54XX },
	{ .div = 34, .val = 33, .flags = RATE_IN_54XX },
	{ .div = 35, .val = 34, .flags = RATE_IN_54XX },
	{ .div = 36, .val = 35, .flags = RATE_IN_54XX },
	{ .div = 37, .val = 36, .flags = RATE_IN_54XX },
	{ .div = 38, .val = 37, .flags = RATE_IN_54XX },
	{ .div = 39, .val = 38, .flags = RATE_IN_54XX },
	{ .div = 40, .val = 39, .flags = RATE_IN_54XX },
	{ .div = 41, .val = 40, .flags = RATE_IN_54XX },
	{ .div = 42, .val = 41, .flags = RATE_IN_54XX },
	{ .div = 43, .val = 42, .flags = RATE_IN_54XX },
	{ .div = 44, .val = 43, .flags = RATE_IN_54XX },
	{ .div = 45, .val = 44, .flags = RATE_IN_54XX },
	{ .div = 46, .val = 45, .flags = RATE_IN_54XX },
	{ .div = 47, .val = 46, .flags = RATE_IN_54XX },
	{ .div = 48, .val = 47, .flags = RATE_IN_54XX },
	{ .div = 49, .val = 48, .flags = RATE_IN_54XX },
	{ .div = 50, .val = 49, .flags = RATE_IN_54XX },
	{ .div = 51, .val = 50, .flags = RATE_IN_54XX },
	{ .div = 52, .val = 51, .flags = RATE_IN_54XX },
	{ .div = 53, .val = 52, .flags = RATE_IN_54XX },
	{ .div = 54, .val = 53, .flags = RATE_IN_54XX },
	{ .div = 55, .val = 54, .flags = RATE_IN_54XX },
	{ .div = 56, .val = 55, .flags = RATE_IN_54XX },
	{ .div = 57, .val = 56, .flags = RATE_IN_54XX },
	{ .div = 58, .val = 57, .flags = RATE_IN_54XX },
	{ .div = 59, .val = 58, .flags = RATE_IN_54XX },
	{ .div = 60, .val = 59, .flags = RATE_IN_54XX },
	{ .div = 61, .val = 60, .flags = RATE_IN_54XX },
	{ .div = 62, .val = 61, .flags = RATE_IN_54XX },
	{ .div = 63, .val = 62, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel dpll_core_h21x2_div[] = {
	{ .parent = &dpll_core_x2_ck, .rates = div63_1to63_rates },
	{ .parent = NULL },
};

static struct clk dpll_core_h21x2_ck = {
	.name		= "dpll_core_h21x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H21_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk c2c_fclk = {
	.name		= "c2c_fclk",
	.parent		= &dpll_core_h21x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk c2c_iclk = {
	.name		= "c2c_iclk",
	.parent		= &c2c_fclk,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk custefuse_sys_gfclk_div = {
	.name		= "custefuse_sys_gfclk_div",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk dpll_core_h11x2_ck = {
	.name		= "dpll_core_h11x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H11_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h12x2_ck = {
	.name		= "dpll_core_h12x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H12_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h13x2_ck = {
	.name		= "dpll_core_h13x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H13_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h14x2_ck = {
	.name		= "dpll_core_h14x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H14_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h22x2_ck = {
	.name		= "dpll_core_h22x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H22_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h23x2_ck = {
	.name		= "dpll_core_h23x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H23_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_core_h24x2_ck = {
	.name		= "dpll_core_h24x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_h21x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H24_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel dpll_core_m2_div[] = {
	{ .parent = &dpll_core_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_core_m2_ck = {
	.name		= "dpll_core_m2_ck",
	.parent		= &dpll_core_ck,
	.clksel		= dpll_core_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel dpll_core_m3x2_div[] = {
	{ .parent = &dpll_core_x2_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_core_m3x2_ck = {
	.name		= "dpll_core_m3x2_ck",
	.parent		= &dpll_core_x2_ck,
	.clksel		= dpll_core_m3x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M3_DPLL_CORE,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk iva_dpll_hs_clk_div = {
	.name		= "iva_dpll_hs_clk_div",
	.parent		= &dpll_core_h12x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

/* DPLL_IVA */
static struct dpll_data dpll_iva_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_IVA,
	.clk_bypass	= &iva_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_IVA,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_IVA,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_IVA,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};


static struct clk dpll_iva_ck = {
	.name		= "dpll_iva_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_iva_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static struct clk dpll_iva_x2_ck = {
	.name		= "dpll_iva_x2_ck",
	.parent		= &dpll_iva_ck,
	.flags		= CLOCK_CLKOUTX2,
	.ops		= &clkops_null,
	.recalc		= &omap3_clkoutx2_recalc,
};

static const struct clksel dpll_iva_h11x2_div[] = {
	{ .parent = &dpll_iva_x2_ck, .rates = div63_1to63_rates },
	{ .parent = NULL },
};

static struct clk dpll_iva_h11x2_ck = {
	.name		= "dpll_iva_h11x2_ck",
	.parent		= &dpll_iva_x2_ck,
	.clksel		= dpll_iva_h11x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H11_DPLL_IVA,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_iva_h12x2_ck = {
	.name		= "dpll_iva_h12x2_ck",
	.parent		= &dpll_iva_x2_ck,
	.clksel		= dpll_iva_h11x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H12_DPLL_IVA,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk mpu_dpll_hs_clk_div = {
	.name		= "mpu_dpll_hs_clk_div",
	.parent		= &dpll_core_h12x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

/* DPLL_MPU */
static struct dpll_data dpll_mpu_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_MPU,
	.clk_bypass	= &mpu_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_MPU,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_MPU,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_MPU,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};


static struct clk dpll_mpu_ck = {
	.name		= "dpll_mpu_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_mpu_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static const struct clksel dpll_mpu_m2_div[] = {
	{ .parent = &dpll_mpu_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_mpu_m2_ck = {
	.name		= "dpll_mpu_m2_ck",
	.parent		= &dpll_mpu_ck,
	.clksel		= dpll_mpu_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_MPU,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk per_dpll_hs_clk_div = {
	.name		= "per_dpll_hs_clk_div",
	.parent		= &dpll_abe_m3x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

/* DPLL_PER */
static struct dpll_data dpll_per_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_PER,
	.clk_bypass	= &per_dpll_hs_clk_div,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_PER,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_PER,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_PER,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 2047,
	.max_divider	= 128,
	.min_divider	= 1,
};


static struct clk dpll_per_ck = {
	.name		= "dpll_per_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_per_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static struct clk dpll_per_x2_ck = {
	.name		= "dpll_per_x2_ck",
	.parent		= &dpll_per_ck,
	.flags		= CLOCK_CLKOUTX2,
	.ops		= &clkops_null,
	.recalc		= &omap3_clkoutx2_recalc,
};

static const struct clksel dpll_per_h11x2_div[] = {
	{ .parent = &dpll_per_x2_ck, .rates = div63_1to63_rates },
	{ .parent = NULL },
};

static struct clk dpll_per_h11x2_ck = {
	.name		= "dpll_per_h11x2_ck",
	.parent		= &dpll_per_x2_ck,
	.clksel		= dpll_per_h11x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H11_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_per_h12x2_ck = {
	.name		= "dpll_per_h12x2_ck",
	.parent		= &dpll_per_x2_ck,
	.clksel		= dpll_per_h11x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H12_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_per_h14x2_ck = {
	.name		= "dpll_per_h14x2_ck",
	.parent		= &dpll_per_x2_ck,
	.clksel		= dpll_per_h11x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_H14_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel dpll_per_m2_div[] = {
	{ .parent = &dpll_per_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_per_m2_ck = {
	.name		= "dpll_per_m2_ck",
	.parent		= &dpll_per_ck,
	.clksel		= dpll_per_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel dpll_per_m2x2_div[] = {
	{ .parent = &dpll_per_x2_ck, .rates = div31_1to31_rates },
	{ .parent = NULL },
};

static struct clk dpll_per_m2x2_ck = {
	.name		= "dpll_per_m2x2_ck",
	.parent		= &dpll_per_x2_ck,
	.clksel		= dpll_per_m2x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dpll_per_m3x2_ck = {
	.name		= "dpll_per_m3x2_ck",
	.parent		= &dpll_per_x2_ck,
	.clksel		= dpll_per_m2x2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M3_DPLL_PER,
	.clksel_mask	= OMAP54XX_DIVHS_0_4_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

/* DPLL_UNIPRO1 */
static struct dpll_data dpll_unipro1_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_UNIPRO1,
	.clk_bypass	= &sys_clkin,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_UNIPRO1,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_UNIPRO1,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_UNIPRO1,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};


static struct clk dpll_unipro1_ck = {
	.name		= "dpll_unipro1_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_unipro1_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static struct clk dpll_unipro1_clkdcoldo = {
	.name		= "dpll_unipro1_clkdcoldo",
	.parent		= &dpll_unipro1_ck,
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_UNIPRO1,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &followparent_recalc,
};

static const struct clksel_rate div127_1to127_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 3, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 4, .val = 3, .flags = RATE_IN_54XX },
	{ .div = 5, .val = 4, .flags = RATE_IN_54XX },
	{ .div = 6, .val = 5, .flags = RATE_IN_54XX },
	{ .div = 7, .val = 6, .flags = RATE_IN_54XX },
	{ .div = 8, .val = 7, .flags = RATE_IN_54XX },
	{ .div = 9, .val = 8, .flags = RATE_IN_54XX },
	{ .div = 10, .val = 9, .flags = RATE_IN_54XX },
	{ .div = 11, .val = 10, .flags = RATE_IN_54XX },
	{ .div = 12, .val = 11, .flags = RATE_IN_54XX },
	{ .div = 13, .val = 12, .flags = RATE_IN_54XX },
	{ .div = 14, .val = 13, .flags = RATE_IN_54XX },
	{ .div = 15, .val = 14, .flags = RATE_IN_54XX },
	{ .div = 16, .val = 15, .flags = RATE_IN_54XX },
	{ .div = 17, .val = 16, .flags = RATE_IN_54XX },
	{ .div = 18, .val = 17, .flags = RATE_IN_54XX },
	{ .div = 19, .val = 18, .flags = RATE_IN_54XX },
	{ .div = 20, .val = 19, .flags = RATE_IN_54XX },
	{ .div = 21, .val = 20, .flags = RATE_IN_54XX },
	{ .div = 22, .val = 21, .flags = RATE_IN_54XX },
	{ .div = 23, .val = 22, .flags = RATE_IN_54XX },
	{ .div = 24, .val = 23, .flags = RATE_IN_54XX },
	{ .div = 25, .val = 24, .flags = RATE_IN_54XX },
	{ .div = 26, .val = 25, .flags = RATE_IN_54XX },
	{ .div = 27, .val = 26, .flags = RATE_IN_54XX },
	{ .div = 28, .val = 27, .flags = RATE_IN_54XX },
	{ .div = 29, .val = 28, .flags = RATE_IN_54XX },
	{ .div = 30, .val = 29, .flags = RATE_IN_54XX },
	{ .div = 31, .val = 30, .flags = RATE_IN_54XX },
	{ .div = 32, .val = 31, .flags = RATE_IN_54XX },
	{ .div = 33, .val = 32, .flags = RATE_IN_54XX },
	{ .div = 34, .val = 33, .flags = RATE_IN_54XX },
	{ .div = 35, .val = 34, .flags = RATE_IN_54XX },
	{ .div = 36, .val = 35, .flags = RATE_IN_54XX },
	{ .div = 37, .val = 36, .flags = RATE_IN_54XX },
	{ .div = 38, .val = 37, .flags = RATE_IN_54XX },
	{ .div = 39, .val = 38, .flags = RATE_IN_54XX },
	{ .div = 40, .val = 39, .flags = RATE_IN_54XX },
	{ .div = 41, .val = 40, .flags = RATE_IN_54XX },
	{ .div = 42, .val = 41, .flags = RATE_IN_54XX },
	{ .div = 43, .val = 42, .flags = RATE_IN_54XX },
	{ .div = 44, .val = 43, .flags = RATE_IN_54XX },
	{ .div = 45, .val = 44, .flags = RATE_IN_54XX },
	{ .div = 46, .val = 45, .flags = RATE_IN_54XX },
	{ .div = 47, .val = 46, .flags = RATE_IN_54XX },
	{ .div = 48, .val = 47, .flags = RATE_IN_54XX },
	{ .div = 49, .val = 48, .flags = RATE_IN_54XX },
	{ .div = 50, .val = 49, .flags = RATE_IN_54XX },
	{ .div = 51, .val = 50, .flags = RATE_IN_54XX },
	{ .div = 52, .val = 51, .flags = RATE_IN_54XX },
	{ .div = 53, .val = 52, .flags = RATE_IN_54XX },
	{ .div = 54, .val = 53, .flags = RATE_IN_54XX },
	{ .div = 55, .val = 54, .flags = RATE_IN_54XX },
	{ .div = 56, .val = 55, .flags = RATE_IN_54XX },
	{ .div = 57, .val = 56, .flags = RATE_IN_54XX },
	{ .div = 58, .val = 57, .flags = RATE_IN_54XX },
	{ .div = 59, .val = 58, .flags = RATE_IN_54XX },
	{ .div = 60, .val = 59, .flags = RATE_IN_54XX },
	{ .div = 61, .val = 60, .flags = RATE_IN_54XX },
	{ .div = 62, .val = 61, .flags = RATE_IN_54XX },
	{ .div = 63, .val = 62, .flags = RATE_IN_54XX },
	{ .div = 64, .val = 63, .flags = RATE_IN_54XX },
	{ .div = 65, .val = 64, .flags = RATE_IN_54XX },
	{ .div = 66, .val = 65, .flags = RATE_IN_54XX },
	{ .div = 67, .val = 66, .flags = RATE_IN_54XX },
	{ .div = 68, .val = 67, .flags = RATE_IN_54XX },
	{ .div = 69, .val = 68, .flags = RATE_IN_54XX },
	{ .div = 70, .val = 69, .flags = RATE_IN_54XX },
	{ .div = 71, .val = 70, .flags = RATE_IN_54XX },
	{ .div = 72, .val = 71, .flags = RATE_IN_54XX },
	{ .div = 73, .val = 72, .flags = RATE_IN_54XX },
	{ .div = 74, .val = 73, .flags = RATE_IN_54XX },
	{ .div = 75, .val = 74, .flags = RATE_IN_54XX },
	{ .div = 76, .val = 75, .flags = RATE_IN_54XX },
	{ .div = 77, .val = 76, .flags = RATE_IN_54XX },
	{ .div = 78, .val = 77, .flags = RATE_IN_54XX },
	{ .div = 79, .val = 78, .flags = RATE_IN_54XX },
	{ .div = 80, .val = 79, .flags = RATE_IN_54XX },
	{ .div = 81, .val = 80, .flags = RATE_IN_54XX },
	{ .div = 82, .val = 81, .flags = RATE_IN_54XX },
	{ .div = 83, .val = 82, .flags = RATE_IN_54XX },
	{ .div = 84, .val = 83, .flags = RATE_IN_54XX },
	{ .div = 85, .val = 84, .flags = RATE_IN_54XX },
	{ .div = 86, .val = 85, .flags = RATE_IN_54XX },
	{ .div = 87, .val = 86, .flags = RATE_IN_54XX },
	{ .div = 88, .val = 87, .flags = RATE_IN_54XX },
	{ .div = 89, .val = 88, .flags = RATE_IN_54XX },
	{ .div = 90, .val = 89, .flags = RATE_IN_54XX },
	{ .div = 91, .val = 90, .flags = RATE_IN_54XX },
	{ .div = 92, .val = 91, .flags = RATE_IN_54XX },
	{ .div = 93, .val = 92, .flags = RATE_IN_54XX },
	{ .div = 94, .val = 93, .flags = RATE_IN_54XX },
	{ .div = 95, .val = 94, .flags = RATE_IN_54XX },
	{ .div = 96, .val = 95, .flags = RATE_IN_54XX },
	{ .div = 97, .val = 96, .flags = RATE_IN_54XX },
	{ .div = 98, .val = 97, .flags = RATE_IN_54XX },
	{ .div = 99, .val = 98, .flags = RATE_IN_54XX },
	{ .div = 100, .val = 99, .flags = RATE_IN_54XX },
	{ .div = 101, .val = 100, .flags = RATE_IN_54XX },
	{ .div = 102, .val = 101, .flags = RATE_IN_54XX },
	{ .div = 103, .val = 102, .flags = RATE_IN_54XX },
	{ .div = 104, .val = 103, .flags = RATE_IN_54XX },
	{ .div = 105, .val = 104, .flags = RATE_IN_54XX },
	{ .div = 106, .val = 105, .flags = RATE_IN_54XX },
	{ .div = 107, .val = 106, .flags = RATE_IN_54XX },
	{ .div = 108, .val = 107, .flags = RATE_IN_54XX },
	{ .div = 109, .val = 108, .flags = RATE_IN_54XX },
	{ .div = 110, .val = 109, .flags = RATE_IN_54XX },
	{ .div = 111, .val = 110, .flags = RATE_IN_54XX },
	{ .div = 112, .val = 111, .flags = RATE_IN_54XX },
	{ .div = 113, .val = 112, .flags = RATE_IN_54XX },
	{ .div = 114, .val = 113, .flags = RATE_IN_54XX },
	{ .div = 115, .val = 114, .flags = RATE_IN_54XX },
	{ .div = 116, .val = 115, .flags = RATE_IN_54XX },
	{ .div = 117, .val = 116, .flags = RATE_IN_54XX },
	{ .div = 118, .val = 117, .flags = RATE_IN_54XX },
	{ .div = 119, .val = 118, .flags = RATE_IN_54XX },
	{ .div = 120, .val = 119, .flags = RATE_IN_54XX },
	{ .div = 121, .val = 120, .flags = RATE_IN_54XX },
	{ .div = 122, .val = 121, .flags = RATE_IN_54XX },
	{ .div = 123, .val = 122, .flags = RATE_IN_54XX },
	{ .div = 124, .val = 123, .flags = RATE_IN_54XX },
	{ .div = 125, .val = 124, .flags = RATE_IN_54XX },
	{ .div = 126, .val = 125, .flags = RATE_IN_54XX },
	{ .div = 127, .val = 126, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel dpll_unipro1_m2_div[] = {
	{ .parent = &dpll_unipro1_ck, .rates = div127_1to127_rates },
	{ .parent = NULL },
};

static struct clk dpll_unipro1_m2_ck = {
	.name		= "dpll_unipro1_m2_ck",
	.parent		= &dpll_unipro1_ck,
	.clksel		= dpll_unipro1_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_UNIPRO1,
	.clksel_mask	= OMAP54XX_DIVHS_0_6_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

/* DPLL_UNIPRO2 */
static struct dpll_data dpll_unipro2_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_UNIPRO2,
	.clk_bypass	= &sys_clkin,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_UNIPRO2,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_UNIPRO2,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_UNIPRO2,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};


static struct clk dpll_unipro2_ck = {
	.name		= "dpll_unipro2_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_unipro2_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
};

static struct clk dpll_unipro2_clkdcoldo = {
	.name		= "dpll_unipro2_clkdcoldo",
	.parent		= &dpll_unipro2_ck,
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_UNIPRO2,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &followparent_recalc,
};

static const struct clksel dpll_unipro2_m2_div[] = {
	{ .parent = &dpll_unipro2_ck, .rates = div127_1to127_rates },
	{ .parent = NULL },
};

static struct clk dpll_unipro2_m2_ck = {
	.name		= "dpll_unipro2_m2_ck",
	.parent		= &dpll_unipro2_ck,
	.clksel		= dpll_unipro2_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_UNIPRO2,
	.clksel_mask	= OMAP54XX_DIVHS_0_6_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk usb_dpll_hs_clk_div = {
	.name		= "usb_dpll_hs_clk_div",
	.parent		= &dpll_abe_m3x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 3,
	.recalc		= &omap_fixed_divisor_recalc,
};

/* DPLL_USB */
static struct dpll_data dpll_usb_dd = {
	.mult_div1_reg	= OMAP54XX_CM_CLKSEL_DPLL_USB,
	.clk_bypass	= &usb_dpll_hs_clk_div,
	.flags		= DPLL_J_TYPE,
	.clk_ref	= &sys_clkin,
	.control_reg	= OMAP54XX_CM_CLKMODE_DPLL_USB,
	.modes		= (1 << DPLL_LOW_POWER_BYPASS) | (1 << DPLL_LOCKED),
	.autoidle_reg	= OMAP54XX_CM_AUTOIDLE_DPLL_USB,
	.idlest_reg	= OMAP54XX_CM_IDLEST_DPLL_USB,
	.mult_mask	= OMAP54XX_DPLL_MULT_MASK,
	.div1_mask	= OMAP54XX_DPLL_DIV_MASK,
	.enable_mask	= OMAP54XX_DPLL_EN_MASK,
	.autoidle_mask	= OMAP54XX_AUTO_DPLL_MODE_MASK,
	.idlest_mask	= OMAP54XX_ST_DPLL_CLK_MASK,
	.sddiv_mask	= OMAP54XX_DPLL_SD_DIV_MASK,
	.max_multiplier	= 4095,
	.max_divider	= 256,
	.min_divider	= 1,
};


static struct clk dpll_usb_ck = {
	.name		= "dpll_usb_ck",
	.parent		= &sys_clkin,
	.dpll_data	= &dpll_usb_dd,
	.init		= &omap2_init_dpll_parent,
	.ops		= &clkops_omap3_noncore_dpll_ops,
	.recalc		= &omap3_dpll_recalc,
	.round_rate	= &omap2_dpll_round_rate,
	.set_rate	= &omap3_noncore_dpll_set_rate,
	.clkdm_name	= "l3init_clkdm",
};

static struct clk dpll_usb_clkdcoldo = {
	.name		= "dpll_usb_clkdcoldo",
	.parent		= &dpll_usb_ck,
	.clksel_reg	= OMAP54XX_CM_CLKDCOLDO_DPLL_USB,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &followparent_recalc,
};

static const struct clksel dpll_usb_m2_div[] = {
	{ .parent = &dpll_usb_ck, .rates = div127_1to127_rates },
	{ .parent = NULL },
};

static struct clk dpll_usb_m2_ck = {
	.name		= "dpll_usb_m2_ck",
	.parent		= &dpll_usb_ck,
	.clksel		= dpll_usb_m2_div,
	.clksel_reg	= OMAP54XX_CM_DIV_M2_DPLL_USB,
	.clksel_mask	= OMAP54XX_DIVHS_0_6_MASK,
	.ops		= &clkops_omap4_dpllmx_ops,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk dss_syc_gfclk_div = {
	.name		= "dss_syc_gfclk_div",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk l3_iclk_div = {
	.name		= "l3_iclk_div",
	.parent		= &dpll_core_h12x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static const struct clksel emif_ll_gclk_mux_sel[] = {
	{ .parent = &c2c_iclk, .rates = div_1_0_rates },
	{ .parent = &l3_iclk_div, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk emif_ll_gclk_mux = {
	.name		= "emif_ll_gclk_mux",
	.parent		= &c2c_iclk,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk func_128m_clk = {
	.name		= "func_128m_clk",
	.parent		= &dpll_per_h11x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk func_12m_fclk = {
	.name		= "func_12m_fclk",
	.parent		= &dpll_per_m2x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 16,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk func_24m_clk = {
	.name		= "func_24m_clk",
	.parent		= &dpll_per_m2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 4,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk func_48m_fclk = {
	.name		= "func_48m_fclk",
	.parent		= &dpll_per_m2x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 4,
	.recalc		= &omap_fixed_divisor_recalc,
};

static struct clk func_96m_fclk = {
	.name		= "func_96m_fclk",
	.parent		= &dpll_per_m2x2_ck,
	.ops		= &clkops_null,
	.fixed_div	= 2,
	.recalc		= &omap_fixed_divisor_recalc,
};

static const struct clksel gpu_core_gclk_mux_sel[] = {
	{ .parent = &dpll_core_h14x2_ck, .rates = div_1_0_rates },
	{ .parent = &dpll_per_h14x2_ck, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk gpu_core_gclk_mux = {
	.name		= "gpu_core_gclk_mux",
	.parent		= &dpll_core_h14x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk gpu_hyd_gclk_mux = {
	.name		= "gpu_hyd_gclk_mux",
	.parent		= &dpll_core_h14x2_ck,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk gpu_l3_iclk = {
	.name		= "gpu_l3_iclk",
	.parent		= &l3_iclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static const struct clksel_rate div2_1to8_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 8, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel l3init_60m_fclk_div[] = {
	{ .parent = &dpll_usb_m2_ck, .rates = div2_1to8_rates },
	{ .parent = NULL },
};

static struct clk l3init_60m_fclk = {
	.name		= "l3init_60m_fclk",
	.parent		= &dpll_usb_m2_ck,
	.clksel		= l3init_60m_fclk_div,
	.clksel_reg	= OMAP54XX_CM_CLKSEL_USB_60MHZ,
	.clksel_mask	= OMAP54XX_CLKSEL_0_0_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel wkupaon_iclk_mux_sel[] = {
	{ .parent = &sys_clkin, .rates = div_1_0_rates },
	{ .parent = &abe_lp_clk_div, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk wkupaon_iclk_mux = {
	.name		= "wkupaon_iclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk l3instr_ts_gclk_div = {
	.name		= "l3instr_ts_gclk_div",
	.parent		= &wkupaon_iclk_mux,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk l4_root_clk_div = {
	.name		= "l4_root_clk_div",
	.parent		= &l3_iclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer10_gfclk_mux = {
	.name		= "timer10_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer11_gfclk_mux = {
	.name		= "timer11_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer1_gfclk_mux = {
	.name		= "timer1_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer2_gfclk_mux = {
	.name		= "timer2_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer3_gfclk_mux = {
	.name		= "timer3_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer4_gfclk_mux = {
	.name		= "timer4_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static const struct clksel timer5_gfclk_mux_sel[] = {
	{ .parent = &dss_syc_gfclk_div, .rates = div_1_0_rates },
	{ .parent = &sys_32k_ck, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk timer5_gfclk_mux = {
	.name		= "timer5_gfclk_mux",
	.parent		= &dss_syc_gfclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer6_gfclk_mux = {
	.name		= "timer6_gfclk_mux",
	.parent		= &dss_syc_gfclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer7_gfclk_mux = {
	.name		= "timer7_gfclk_mux",
	.parent		= &dss_syc_gfclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer8_gfclk_mux = {
	.name		= "timer8_gfclk_mux",
	.parent		= &dss_syc_gfclk_div,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

static struct clk timer9_gfclk_mux = {
	.name		= "timer9_gfclk_mux",
	.parent		= &sys_clkin,
	.ops		= &clkops_null,
	.recalc		= &followparent_recalc,
};

/* Leaf clocks controlled by modules */

/* Remaining optional clocks */
static const struct clksel_rate div2_1to2_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static const struct clksel aess_fclk_div[] = {
	{ .parent = &abe_clk, .rates = div2_1to2_rates },
	{ .parent = NULL },
};

static struct clk aess_fclk = {
	.name		= "aess_fclk",
	.parent		= &abe_clk,
	.clksel		= aess_fclk_div,
	.clksel_reg	= OMAP54XX_CM_ABE_AESS_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_AESS_FCLK_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel dmic_sync_mux_sel[] = {
	{ .parent = &abe_24m_fclk, .rates = div_1_0_rates },
	{ .parent = &dss_syc_gfclk_div, .rates = div_1_1_rates },
	{ .parent = &func_24m_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk dmic_sync_mux_ck = {
	.name		= "dmic_sync_mux_ck",
	.parent		= &abe_24m_fclk,
	.clksel		= dmic_sync_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_DMIC_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_INTERNAL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel dmic_gfclk_sel[] = {
	{ .parent = &dmic_sync_mux_ck, .rates = div_1_0_rates },
	{ .parent = &pad_clks, .rates = div_1_1_rates },
	{ .parent = &slimbus_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk dmic_gfclk = {
	.name		= "dmic_gfclk",
	.parent		= &dmic_sync_mux_ck,
	.clksel		= dmic_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_DMIC_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel fdif_fclk_div[] = {
	{ .parent = &dpll_per_h11x2_ck, .rates = div2_1to2_rates },
	{ .parent = NULL },
};

static struct clk fdif_fclk = {
	.name		= "fdif_fclk",
	.parent		= &dpll_per_h11x2_ck,
	.clksel		= fdif_fclk_div,
	.clksel_reg	= OMAP54XX_CM_CAM_FDIF_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_FCLK_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel hsi_fclk_div[] = {
	{ .parent = &dpll_per_m2x2_ck, .rates = div2_1to2_rates },
	{ .parent = NULL },
};

static struct clk hsi_fclk = {
	.name		= "hsi_fclk",
	.parent		= &dpll_per_m2x2_ck,
	.clksel		= hsi_fclk_div,
	.clksel_reg	= OMAP54XX_CM_L3INIT_HSI_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk mcasp_sync_mux_ck = {
	.name		= "mcasp_sync_mux_ck",
	.parent		= &abe_24m_fclk,
	.clksel		= dmic_sync_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCASP_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_INTERNAL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mcasp_gfclk_sel[] = {
	{ .parent = &mcasp_sync_mux_ck, .rates = div_1_0_rates },
	{ .parent = &pad_clks, .rates = div_1_1_rates },
	{ .parent = &slimbus_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk mcasp_gfclk = {
	.name		= "mcasp_gfclk",
	.parent		= &mcasp_sync_mux_ck,
	.clksel		= mcasp_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCASP_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk mcbsp1_sync_mux_ck = {
	.name		= "mcbsp1_sync_mux_ck",
	.parent		= &abe_24m_fclk,
	.clksel		= dmic_sync_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP1_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_INTERNAL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mcbsp1_gfclk_sel[] = {
	{ .parent = &mcbsp1_sync_mux_ck, .rates = div_1_0_rates },
	{ .parent = &pad_clks, .rates = div_1_1_rates },
	{ .parent = &slimbus_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk mcbsp1_gfclk = {
	.name		= "mcbsp1_gfclk",
	.parent		= &mcbsp1_sync_mux_ck,
	.clksel		= mcbsp1_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP1_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk mcbsp2_sync_mux_ck = {
	.name		= "mcbsp2_sync_mux_ck",
	.parent		= &abe_24m_fclk,
	.clksel		= dmic_sync_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP2_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_INTERNAL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mcbsp2_gfclk_sel[] = {
	{ .parent = &mcbsp2_sync_mux_ck, .rates = div_1_0_rates },
	{ .parent = &pad_clks, .rates = div_1_1_rates },
	{ .parent = &slimbus_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk mcbsp2_gfclk = {
	.name		= "mcbsp2_gfclk",
	.parent		= &mcbsp2_sync_mux_ck,
	.clksel		= mcbsp2_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP2_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk mcbsp3_sync_mux_ck = {
	.name		= "mcbsp3_sync_mux_ck",
	.parent		= &abe_24m_fclk,
	.clksel		= dmic_sync_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP3_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_INTERNAL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mcbsp3_gfclk_sel[] = {
	{ .parent = &mcbsp3_sync_mux_ck, .rates = div_1_0_rates },
	{ .parent = &pad_clks, .rates = div_1_1_rates },
	{ .parent = &slimbus_clk, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static struct clk mcbsp3_gfclk = {
	.name		= "mcbsp3_gfclk",
	.parent		= &mcbsp3_sync_mux_ck,
	.clksel		= mcbsp3_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_ABE_MCBSP3_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mmc1_fclk_mux_sel[] = {
	{ .parent = &func_128m_clk, .rates = div_1_0_rates },
	{ .parent = &dpll_per_m2x2_ck, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk mmc1_fclk_mux = {
	.name		= "mmc1_fclk_mux",
	.parent		= &func_128m_clk,
	.clksel		= mmc1_fclk_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_L3INIT_MMC1_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mmc1_fclk_div[] = {
	{ .parent = &mmc1_fclk_mux, .rates = div2_1to2_rates },
	{ .parent = NULL },
};

static struct clk mmc1_fclk = {
	.name		= "mmc1_fclk",
	.parent		= &mmc1_fclk_mux,
	.clksel		= mmc1_fclk_div,
	.clksel_reg	= OMAP54XX_CM_L3INIT_MMC1_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_DIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk mmc2_fclk_mux = {
	.name		= "mmc2_fclk_mux",
	.parent		= &func_128m_clk,
	.clksel		= mmc1_fclk_mux_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_L3INIT_MMC2_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_SOURCE_24_24_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel mmc2_fclk_div[] = {
	{ .parent = &mmc2_fclk_mux, .rates = div2_1to2_rates },
	{ .parent = NULL },
};

static struct clk mmc2_fclk = {
	.name		= "mmc2_fclk",
	.parent		= &mmc2_fclk_mux,
	.clksel		= mmc2_fclk_div,
	.clksel_reg	= OMAP54XX_CM_L3INIT_MMC2_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_DIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel utmi_p1_gfclk_sel[] = {
	{ .parent = &l3init_60m_fclk, .rates = div_1_0_rates },
	{ .parent = &xclk60mhsp1, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk utmi_p1_gfclk = {
	.name		= "utmi_p1_gfclk",
	.parent		= &l3init_60m_fclk,
	.clksel		= utmi_p1_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_UTMI_P1_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

static const struct clksel utmi_p2_gfclk_sel[] = {
	{ .parent = &l3init_60m_fclk, .rates = div_1_0_rates },
	{ .parent = &xclk60mhsp2, .rates = div_1_1_rates },
	{ .parent = NULL },
};

static struct clk utmi_p2_gfclk = {
	.name		= "utmi_p2_gfclk",
	.parent		= &l3init_60m_fclk,
	.clksel		= utmi_p2_gfclk_sel,
	.init		= &omap2_init_clksel_parent,
	.clksel_reg	= OMAP54XX_CM_L3INIT_USB_HOST_HS_CLKCTRL,
	.clksel_mask	= OMAP54XX_CLKSEL_UTMI_P2_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
};

/* SCRM aux clk nodes */

static const struct clksel auxclk_src_sel[] = {
	{ .parent = &sys_clkin, .rates = div_1_0_rates },
	{ .parent = &dpll_core_m3x2_ck, .rates = div_1_1_rates },
	{ .parent = &dpll_per_m3x2_ck, .rates = div_1_2_rates },
	{ .parent = NULL },
};

static const struct clksel_rate div16_1to16_rates[] = {
	{ .div = 1, .val = 0, .flags = RATE_IN_54XX },
	{ .div = 2, .val = 1, .flags = RATE_IN_54XX },
	{ .div = 3, .val = 2, .flags = RATE_IN_54XX },
	{ .div = 4, .val = 3, .flags = RATE_IN_54XX },
	{ .div = 5, .val = 4, .flags = RATE_IN_54XX },
	{ .div = 6, .val = 5, .flags = RATE_IN_54XX },
	{ .div = 7, .val = 6, .flags = RATE_IN_54XX },
	{ .div = 8, .val = 7, .flags = RATE_IN_54XX },
	{ .div = 9, .val = 8, .flags = RATE_IN_54XX },
	{ .div = 10, .val = 9, .flags = RATE_IN_54XX },
	{ .div = 11, .val = 10, .flags = RATE_IN_54XX },
	{ .div = 12, .val = 11, .flags = RATE_IN_54XX },
	{ .div = 13, .val = 12, .flags = RATE_IN_54XX },
	{ .div = 14, .val = 13, .flags = RATE_IN_54XX },
	{ .div = 15, .val = 14, .flags = RATE_IN_54XX },
	{ .div = 16, .val = 15, .flags = RATE_IN_54XX },
	{ .div = 0 },
};

static struct clk auxclk0_src_ck = {
	.name		= "auxclk0_src_ck",
	.parent		= &sys_clkin,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_omap2_dflt,
	.clksel		= auxclk_src_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK0,
	.clksel_mask	= OMAP5_SRCSELECT_MASK,
	.recalc		= &omap2_clksel_recalc,
	.enable_reg	= OMAP5_SCRM_AUXCLK0,
	.enable_bit	= OMAP5_ENABLE_SHIFT,
};

static const struct clksel auxclk0_sel[] = {
	{ .parent = &auxclk0_src_ck, .rates = div16_1to16_rates },
	{ .parent = NULL },
};

static struct clk auxclk0_ck = {
	.name		= "auxclk0_ck",
	.parent		= &auxclk0_src_ck,
	.clksel		= auxclk0_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK0,
	.clksel_mask	= OMAP5_CLKDIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk auxclk1_src_ck = {
	.name		= "auxclk1_src_ck",
	.parent		= &sys_clkin,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_omap2_dflt,
	.clksel		= auxclk_src_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK1,
	.clksel_mask	= OMAP5_SRCSELECT_MASK,
	.recalc		= &omap2_clksel_recalc,
	.enable_reg	= OMAP5_SCRM_AUXCLK1,
	.enable_bit	= OMAP5_ENABLE_SHIFT,
};

static const struct clksel auxclk1_sel[] = {
	{ .parent = &auxclk1_src_ck, .rates = div16_1to16_rates },
	{ .parent = NULL },
};

static struct clk auxclk1_ck = {
	.name		= "auxclk1_ck",
	.parent		= &auxclk1_src_ck,
	.clksel		= auxclk1_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK1,
	.clksel_mask	= OMAP5_CLKDIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk auxclk2_src_ck = {
	.name		= "auxclk2_src_ck",
	.parent		= &sys_clkin,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_omap2_dflt,
	.clksel		= auxclk_src_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK2,
	.clksel_mask	= OMAP5_SRCSELECT_MASK,
	.recalc		= &omap2_clksel_recalc,
	.enable_reg	= OMAP5_SCRM_AUXCLK2,
	.enable_bit	= OMAP5_ENABLE_SHIFT,
};

static const struct clksel auxclk2_sel[] = {
	{ .parent = &auxclk2_src_ck, .rates = div16_1to16_rates },
	{ .parent = NULL },
};

static struct clk auxclk2_ck = {
	.name		= "auxclk2_ck",
	.parent		= &auxclk2_src_ck,
	.clksel		= auxclk2_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK2,
	.clksel_mask	= OMAP5_CLKDIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static struct clk auxclk3_src_ck = {
	.name		= "auxclk3_src_ck",
	.parent		= &sys_clkin,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_omap2_dflt,
	.clksel		= auxclk_src_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK3,
	.clksel_mask	= OMAP5_SRCSELECT_MASK,
	.recalc		= &omap2_clksel_recalc,
	.enable_reg	= OMAP5_SCRM_AUXCLK3,
	.enable_bit	= OMAP5_ENABLE_SHIFT,
};

static const struct clksel auxclk3_sel[] = {
	{ .parent = &auxclk3_src_ck, .rates = div16_1to16_rates },
	{ .parent = NULL },
};

static struct clk auxclk3_ck = {
	.name		= "auxclk3_ck",
	.parent		= &auxclk3_src_ck,
	.clksel		= auxclk3_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLK3,
	.clksel_mask	= OMAP5_CLKDIV_MASK,
	.ops		= &clkops_null,
	.recalc		= &omap2_clksel_recalc,
	.round_rate	= &omap2_clksel_round_rate,
	.set_rate	= &omap2_clksel_set_rate,
};

static const struct clksel auxclkreq_sel[] = {
	{ .parent = &auxclk0_ck, .rates = div_1_0_rates },
	{ .parent = &auxclk1_ck, .rates = div_1_1_rates },
	{ .parent = &auxclk2_ck, .rates = div_1_2_rates },
	{ .parent = &auxclk3_ck, .rates = div_1_3_rates },
	{ .parent = &auxclk4_ck, .rates = div_1_4_rates },
	{ .parent = &auxclk5_ck, .rates = div_1_5_rates },
	{ .parent = NULL },
};

static struct clk auxclkreq0_ck = {
	.name		= "auxclkreq0_ck",
	.parent		= &auxclk0_ck,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_null,
	.clksel		= auxclkreq_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLKREQ0,
	.clksel_mask	= OMAP5_MAPPING_MASK,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk auxclkreq1_ck = {
	.name		= "auxclkreq1_ck",
	.parent		= &auxclk1_ck,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_null,
	.clksel		= auxclkreq_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLKREQ1,
	.clksel_mask	= OMAP5_MAPPING_MASK,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk auxclkreq2_ck = {
	.name		= "auxclkreq2_ck",
	.parent		= &auxclk2_ck,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_null,
	.clksel		= auxclkreq_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLKREQ2,
	.clksel_mask	= OMAP5_MAPPING_MASK,
	.recalc		= &omap2_clksel_recalc,
};

static struct clk auxclkreq3_ck = {
	.name		= "auxclkreq3_ck",
	.parent		= &auxclk3_ck,
	.init		= &omap2_init_clksel_parent,
	.ops		= &clkops_null,
	.clksel		= auxclkreq_sel,
	.clksel_reg	= OMAP5_SCRM_AUXCLKREQ3,
	.clksel_mask	= OMAP5_MAPPING_MASK,
	.recalc		= &omap2_clksel_recalc,
};

/*
 * clkdev
 */

static struct omap_clk omap54xx_clks[] = {
	CLK(NULL,	"pad_clks",			&pad_clks,	CK_54XX),
	CLK(NULL,	"secure_32k_clk_src",		&secure_32k_clk_src,	CK_54XX),
	CLK(NULL,	"slimbus_clk",			&slimbus_clk,	CK_54XX),
	CLK(NULL,	"sys_32k_ck",			&sys_32k_ck,	CK_54XX),
	CLK(NULL,	"virt_12000000_ck",		&virt_12000000_ck,	CK_54XX),
	CLK(NULL,	"virt_13000000_ck",		&virt_13000000_ck,	CK_54XX),
	CLK(NULL,	"virt_16800000_ck",		&virt_16800000_ck,	CK_54XX),
	CLK(NULL,	"virt_19200000_ck",		&virt_19200000_ck,	CK_54XX),
	CLK(NULL,	"virt_26000000_ck",		&virt_26000000_ck,	CK_54XX),
	CLK(NULL,	"virt_27000000_ck",		&virt_27000000_ck,	CK_54XX),
	CLK(NULL,	"virt_38400000_ck",		&virt_38400000_ck,	CK_54XX),
	CLK(NULL,	"sys_clkin",			&sys_clkin,	CK_54XX),
	CLK(NULL,	"xclk60mhsp1",			&xclk60mhsp1,	CK_54XX),
	CLK(NULL,	"xclk60mhsp2",			&xclk60mhsp2,	CK_54XX),
	CLK(NULL,	"abe_dpll_bypass_clk_mux",	&abe_dpll_bypass_clk_mux,	CK_54XX),
	CLK(NULL,	"abe_dpll_clk_mux",		&abe_dpll_clk_mux,	CK_54XX),
	CLK(NULL,	"dpll_abe_ck",			&dpll_abe_ck,	CK_54XX),
	CLK(NULL,	"dpll_abe_x2_ck",		&dpll_abe_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_abe_m2x2_ck",		&dpll_abe_m2x2_ck,	CK_54XX),
	CLK(NULL,	"abe_24m_fclk",			&abe_24m_fclk,	CK_54XX),
	CLK(NULL,	"abe_clk",			&abe_clk,	CK_54XX),
	CLK(NULL,	"abe_iclk",			&abe_iclk,	CK_54XX),
	CLK(NULL,	"abe_lp_clk_div",		&abe_lp_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_abe_m3x2_ck",		&dpll_abe_m3x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_ck",			&dpll_core_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_x2_ck",		&dpll_core_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h21x2_ck",		&dpll_core_h21x2_ck,	CK_54XX),
	CLK(NULL,	"c2c_fclk",			&c2c_fclk,	CK_54XX),
	CLK(NULL,	"c2c_iclk",			&c2c_iclk,	CK_54XX),
	CLK(NULL,	"custefuse_sys_gfclk_div",	&custefuse_sys_gfclk_div,	CK_54XX),
	CLK(NULL,	"dpll_core_h11x2_ck",		&dpll_core_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h12x2_ck",		&dpll_core_h12x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h13x2_ck",		&dpll_core_h13x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h14x2_ck",		&dpll_core_h14x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h22x2_ck",		&dpll_core_h22x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h23x2_ck",		&dpll_core_h23x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_h24x2_ck",		&dpll_core_h24x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_m2_ck",		&dpll_core_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_core_m3x2_ck",		&dpll_core_m3x2_ck,	CK_54XX),
	CLK(NULL,	"iva_dpll_hs_clk_div",		&iva_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_iva_ck",			&dpll_iva_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_x2_ck",		&dpll_iva_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_h11x2_ck",		&dpll_iva_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_iva_h12x2_ck",		&dpll_iva_h12x2_ck,	CK_54XX),
	CLK(NULL,	"mpu_dpll_hs_clk_div",		&mpu_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_mpu_ck",			&dpll_mpu_ck,	CK_54XX),
	CLK(NULL,	"dpll_mpu_m2_ck",		&dpll_mpu_m2_ck,	CK_54XX),
	CLK(NULL,	"per_dpll_hs_clk_div",		&per_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_per_ck",			&dpll_per_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_x2_ck",		&dpll_per_x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h11x2_ck",		&dpll_per_h11x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h12x2_ck",		&dpll_per_h12x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_h14x2_ck",		&dpll_per_h14x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m2_ck",		&dpll_per_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m2x2_ck",		&dpll_per_m2x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_per_m3x2_ck",		&dpll_per_m3x2_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_ck",		&dpll_unipro1_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_clkdcoldo",	&dpll_unipro1_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_unipro1_m2_ck",		&dpll_unipro1_m2_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_ck",		&dpll_unipro2_ck,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_clkdcoldo",	&dpll_unipro2_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_unipro2_m2_ck",		&dpll_unipro2_m2_ck,	CK_54XX),
	CLK(NULL,	"usb_dpll_hs_clk_div",		&usb_dpll_hs_clk_div,	CK_54XX),
	CLK(NULL,	"dpll_usb_ck",			&dpll_usb_ck,	CK_54XX),
	CLK(NULL,	"dpll_usb_clkdcoldo",		&dpll_usb_clkdcoldo,	CK_54XX),
	CLK(NULL,	"dpll_usb_m2_ck",		&dpll_usb_m2_ck,	CK_54XX),
	CLK(NULL,	"dss_syc_gfclk_div",		&dss_syc_gfclk_div,	CK_54XX),
	CLK(NULL,	"l3_iclk_div",			&l3_iclk_div,	CK_54XX),
	CLK(NULL,	"emif_ll_gclk_mux",		&emif_ll_gclk_mux,	CK_54XX),
	CLK(NULL,	"func_128m_clk",		&func_128m_clk,	CK_54XX),
	CLK(NULL,	"func_12m_fclk",		&func_12m_fclk,	CK_54XX),
	CLK(NULL,	"func_24m_clk",			&func_24m_clk,	CK_54XX),
	CLK(NULL,	"func_48m_fclk",		&func_48m_fclk,	CK_54XX),
	CLK(NULL,	"func_96m_fclk",		&func_96m_fclk,	CK_54XX),
	CLK(NULL,	"gpu_core_gclk_mux",		&gpu_core_gclk_mux,	CK_54XX),
	CLK(NULL,	"gpu_hyd_gclk_mux",		&gpu_hyd_gclk_mux,	CK_54XX),
	CLK(NULL,	"gpu_l3_iclk",			&gpu_l3_iclk,	CK_54XX),
	CLK(NULL,	"l3init_60m_fclk",		&l3init_60m_fclk,	CK_54XX),
	CLK(NULL,	"wkupaon_iclk_mux",		&wkupaon_iclk_mux,	CK_54XX),
	CLK(NULL,	"l3instr_ts_gclk_div",		&l3instr_ts_gclk_div,	CK_54XX),
	CLK(NULL,	"l4_root_clk_div",		&l4_root_clk_div,	CK_54XX),
	CLK(NULL,	"timer10_gfclk_mux",		&timer10_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer11_gfclk_mux",		&timer11_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer1_gfclk_mux",		&timer1_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer2_gfclk_mux",		&timer2_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer3_gfclk_mux",		&timer3_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer4_gfclk_mux",		&timer4_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer5_gfclk_mux",		&timer5_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer6_gfclk_mux",		&timer6_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer7_gfclk_mux",		&timer7_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer8_gfclk_mux",		&timer8_gfclk_mux,	CK_54XX),
	CLK(NULL,	"timer9_gfclk_mux",		&timer9_gfclk_mux,	CK_54XX),
	CLK(NULL,	"aess_fclk",			&aess_fclk,	CK_54XX),
	CLK(NULL,	"dmic_sync_mux_ck",		&dmic_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"dmic_gfclk",			&dmic_gfclk,	CK_54XX),
	CLK(NULL,	"fdif_fclk",			&fdif_fclk,	CK_54XX),
	CLK(NULL,	"hsi_fclk",			&hsi_fclk,	CK_54XX),
	CLK(NULL,	"mcasp_sync_mux_ck",		&mcasp_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcasp_gfclk",			&mcasp_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp1_sync_mux_ck",		&mcbsp1_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp1_gfclk",			&mcbsp1_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp2_sync_mux_ck",		&mcbsp2_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp2_gfclk",			&mcbsp2_gfclk,	CK_54XX),
	CLK(NULL,	"mcbsp3_sync_mux_ck",		&mcbsp3_sync_mux_ck,	CK_54XX),
	CLK(NULL,	"mcbsp3_gfclk",			&mcbsp3_gfclk,	CK_54XX),
	CLK(NULL,	"mmc1_fclk_mux",		&mmc1_fclk_mux,	CK_54XX),
	CLK(NULL,	"mmc1_fclk",			&mmc1_fclk,	CK_54XX),
	CLK(NULL,	"mmc2_fclk_mux",		&mmc2_fclk_mux,	CK_54XX),
	CLK(NULL,	"mmc2_fclk",			&mmc2_fclk,	CK_54XX),
	CLK(NULL,	"utmi_p1_gfclk",		&utmi_p1_gfclk,	CK_54XX),
	CLK(NULL,	"utmi_p2_gfclk",		&utmi_p2_gfclk,	CK_54XX),
	CLK(NULL,	"auxclk0_src_ck",		&auxclk0_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk0_ck",			&auxclk0_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq0_ck",		&auxclkreq0_ck,	CK_54XX),
	CLK(NULL,	"auxclk1_src_ck",		&auxclk1_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk1_ck",			&auxclk1_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq1_ck",		&auxclkreq1_ck,	CK_54XX),
	CLK(NULL,	"auxclk2_src_ck",		&auxclk2_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk2_ck",			&auxclk2_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq2_ck",		&auxclkreq2_ck,	CK_54XX),
	CLK(NULL,	"auxclk3_src_ck",		&auxclk3_src_ck,	CK_54XX),
	CLK(NULL,	"auxclk3_ck",			&auxclk3_ck,	CK_54XX),
	CLK(NULL,	"auxclkreq3_ck",		&auxclkreq3_ck,	CK_54XX),
	CLK(NULL,	"gpmc_ck",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_i2c.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"mailboxes_ick",		&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.0",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap_hsmmc.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap-mcbsp.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.1",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.2",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.3",	"ick",			&dummy_ck,	CK_54XX),
	CLK("omap2_mcspi.4",	"ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart1_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart2_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart3_ick",			&dummy_ck,	CK_54XX),
	CLK(NULL,	"uart4_ick",			&dummy_ck,	CK_54XX),
	CLK("usbhs_omap",	"usbhost_ick",		&dummy_ck,	CK_54XX),
	CLK("usbhs_omap",	"usbtll_fck",		&dummy_ck,	CK_54XX),
	CLK("omap_wdt",	"ick",				&dummy_ck,	CK_54XX),
	CLK("omap_timer.1",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.2",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.3",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.4",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.5",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.6",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.7",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.8",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.9",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.10",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.11",	"32k_ck",		&sys_32k_ck,	CK_54XX),
	CLK("omap_timer.1",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.2",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.3",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.4",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.9",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.10",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.11",	"sys_ck",		&sys_clkin_ck,	CK_54XX),
	CLK("omap_timer.5",	"sys_ck",		&syc_clk_div_ck,	CK_54XX),
	CLK("omap_timer.6",	"sys_ck",		&syc_clk_div_ck,	CK_54XX),
	CLK("omap_timer.7",	"sys_ck",		&syc_clk_div_ck,	CK_54XX),
	CLK("omap_timer.8",	"sys_ck",		&syc_clk_div_ck,	CK_54XX),
};

int __init omap5xxx_clk_init(void)
{
	struct omap_clk *c;
	u32 cpu_clkflg;

	if (cpu_is_omap54xx()) {
		cpu_mask = RATE_IN_54XX;
		cpu_clkflg = CK_54XX;
	}

	clk_init(&omap2_clk_functions);

	/*
	 * Must stay commented until all OMAP SoC drivers are
	 * converted to runtime PM, or drivers may start crashing
	 *
	 * omap2_clk_disable_clkdm_control();
	 */

	for (c = omap54xx_clks; c < omap54xx_clks + ARRAY_SIZE(omap54xx_clks);
									  c++)
		clk_preinit(c->lk.clk);

	for (c = omap54xx_clks; c < omap54xx_clks + ARRAY_SIZE(omap54xx_clks);
									  c++)
		if (c->cpu & cpu_clkflg) {
			clkdev_add(&c->lk);
			clk_register(c->lk.clk);
			omap2_init_clk_clkdm(c->lk.clk);
		}

	/* Disable autoidle on all clocks; let the PM code enable it later */
	omap_clk_disable_autoidle_all();

	recalculate_root_clocks();

	/*
	 * Only enable those clocks we will need, let the drivers
	 * enable other clocks as necessary
	 */
	clk_enable_init_clocks();

	return 0;
}
