/*
 * debugss.c: Debug Sus-System related code goes in here
 *
 * Copyright (C) {2013} Texas Instruments Incorporated - http://www.ti.com/
 *
 * This file is automatically generated from the AM33XX hardware databases.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include <linux/init.h>
#include <linux/err.h>
#include <linux/clk.h>

#include "omap_hwmod.h"

static bool is_debugss_en;

/**
 * omap_debugss_en - Enable debugss clock/module based on user config
 *
 * During kernel bootup, omap2 hwmod framework will disable all the
 * unused/unclaimed modules, which in turn also disables debugss module.
 * This breaks any further debugging capability provided by HW.
 *
 *
 * Introduce early param which allows user to enable clock/module -
 *
 *   omap_debugss_en	(For all OMAP2 architectures)
 *
 * Please note that, with this command-line param, module always remain
 * enabled.
 */
static int __init omap_debugss_en(char *str)
{
	is_debugss_en = true;
	return 0;
}
early_param("omap_debugss_en", omap_debugss_en);

static int __init _omap2_debugss_enable(void)
{
	const char oh_name[10] = "debugss";
	struct omap_hwmod *oh;
	int ret;

	if (is_debugss_en) {
		struct omap_hwmod_opt_clk *oc;
		int i;

		oh = omap_hwmod_lookup(oh_name);
		if (!oh) {
			pr_err("debugss device not found\n");
			return 0;
		}

		/* Make sure that hwmod internal data structures are setup */
		ret = omap_hwmod_setup_one(oh_name);
		if (ret) {
			pr_err("failed to setup hwmod for %s\n", oh_name);
			return 0;
		}
		/* Enable optional clocks */
		for (i = oh->opt_clks_cnt, oc = oh->opt_clks; i > 0; i--, oc++)	{
			if (oc->_clk)
				clk_prepare_enable(oc->_clk);
		}
		/* Enable debugss clock/module  */
		omap_hwmod_enable(oh);
	}

	return 0;
}
device_initcall(_omap2_debugss_enable);
