#
# linux/drivers/power/fg/Makefile
#
# Makefile for TI Fuel Gauge
#
# Copyright (C) 2008-2009 Texas Instruments, Inc.
# Author: Texas Instruments, Inc.
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# THIS PACKAGE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.

ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-y									+= fg.o fg_math.o fg_edv.o fg_ocv.o
